- patches/coreboot-4.5.patch
See https://github.com/coreboot/coreboot/commit/8bbd596de631adc8b677e69603e978b848eb1708
> Fix coreboot build where gcc defaults to pie (issue #177)

- patches/coreboot-4.7.patch
If USE_OPTION_TABLE is not set when building coreboot, cbfs_boot_map_with_leak() within src/lib/cbfs.c is not called by smm codes, and will be stripped out at link time, otherwise, other modules may call cbfs_boot_map_with_leak() within smm codes, which breaks its build for prog_segment_loaded() is not built for smm codes (tested when building for Thinkpad x230 with USE_OPTION_TABLE enabled).
I believe that prog_segment_loaded() is not intended to be called within smm codes, so I create this patch, not to call prog_segment_loaded in smm, which enables us to set USE_OPTION_TABLE and STATIC_OPTION_TABLE to make tuning cmos options easier while keeping security.
More previous info could be found on #285, which is closed due to branch reform.
> Changed to coreboot patch not to call prog_segment_loaded in smm.

- initrd/init
To avoid unnecessary errors, only load the eth0 network if the e1000
module exists. Also remove /bin/ash so CONFIG_BOOTSCRIPT works.
> Make eth0 init condition on module, remove early bin/ash

- Makefile
- modules/newt
- modules/slang
The whiptail binary will allow us to create GUI menus from bash scripts.
It is included in the newt library, which depends on slang. To enable,
the board configuration file should add CONFIG_SLANG=y and CONFIG_NEWT=y
> Add whiptail binary, new libraries, and slang dependency

- Makefile
"export" statements included or declared in a Makefile proves literally
(with no escape) passed to the shell, which may result in shell envvars
containing literal double quote if SHELL is set as bash, and they further
becomes statements containing `\"` when printed with command export.
This behavior could be observed by the makefile inlined at the end.
This commit adds a regexp to sed to remove those `\"`.
export QUOTE="QUOTE"
SHELL := /bin/bash
.SHELLFLAGS := -o pipefail -c
export-quote:
export|grep QUOTE
> Walkaround envvars passed through make(1) when generating etc/config

- initrd/bin/gui-init
- initrd/bin/kexec-select-boot
The point of this change is to provide a failsafe (failunsafe?) mode for
less technically-savvy users who will ultimately be using Heads by
default on Librem laptops.
There are some scenarios where an end user might forget to update hashes
in /boot after an initrd change or might have some other hash mismatch.
Currently that user would then be stuck in a recovery console in Heads
not knowing what to do within that limited shell environment to fix the
situation.
This change adds a 'force' mode to kexec-select-boot that goes straight
into a boot menu and bypasses the hash checks so the user could more
easily get back into their system to attempt to repair it. It adds
appropriate warnings about why this is a risky option and moves it down
toward the bottom of the menu. The goal would be to …
> Add a "force" option to kexec-select-boot to bypass hash checks

- initrd/bin/gui-init
- initrd/bin/kexec-select-boot
When hashes mismatch in kexec-select-boot the user just gets dumped to a recovery console and often the suspect file has scrolled off of the screen. This change creates a GUI menu when in GUI mode that alerts the user to which file(s) failed before dumping them to a recovery menu.
> Add a gui message when hash checks fail in kexec-select-boot

- modules/newt
- modules/slang
If you have tcl-devel installed locally, newt will try to compile the Tcl extension, which will fail, and slang configure will complain about 'file already exists' when recompiling.
> Fixes for newt and slang modules

- initrd/bin/gui-init
One of the other core functions a user needs when bootstrapping is
taking over the TPM. I've added a new option in the menu for this and it
revealed that some of the menus needed more space so I've widened all
the menus and also made the main menu longer so the options don't
scroll.
> Add a menu option to reset TPM for bootstrapping. Widen menus.

- Makefile
- patches/coreboot-4.7/0001-intel-fsp-Fix-TPM-initialization-when-vboot-is-disab.patch
- patches/coreboot-4.7/0003-soc-intel-skylake-Enable-VT-d-and-X2APIC.patch
- patches/coreboot-4.7/0004-soc-intel-skylake-Generate-ACPI-DMAR-table.patch
- patches/coreboot-4.7/0005-purism-librem_skl-Enable-TPM-support.patch
- patches/coreboot-4.7/0006-purism-librem_skl-Explicitely-enable-VMX-and-Intel-S.patch
- patches/coreboot-4.7/0007-intel-fsp-fsp2_0-Fix-FSP-2.0-headers-to-match-github.patch
- patches/coreboot-4.7/0009-Add-heads-TPM-measurements-to-Skylake-Kabylake.patch
- patches/coreboot-4.7/0013-intel-cpu-Fix-SpeedStep-enabling.patch
- patches/coreboot-4.7/0014-purism-librem_skl-Set-TCC-Activation-at-95C.patch
- patches/coreboot-4.7/0015-purism-librem_skl-Fix-Librem-15-v3-devicetree-config.patch
Coreboot patches are becoming hard to maintain, and resolving conflicts in the patch if two people decide to update the patch file makes it even harder. 
This adds the ability to use a .series file which contains filenames for patches to apply. 
Also add various patches to coreboot 4.7 to add measured boot support to skylake devices, as well as IOMMU, and TPM support to librem 13v2.
> Add ability to specify series of patches

- initrd/bin/gui-init
The number of options we want in the menu is starting to get large
enough that it's worth slimming things down in the main menu and move
options to nested menus. Along with this nested menu change is the
option to re-sign and re-hash files in /boot directly from the menu.
> Create nested menus and add option to rehash/sign /boot

- initrd/bin/gui-init
Part of the Heads workflow involves handling legitimate changes to /boot
as part of the package manager. This is a challenging workflow to handle
as package managers on many systems work in a completely unattended way
(and some even reboot first, apply updates, and then reboot again).
We need to be able to detect changes that are potentially caused by a
package manager so to do that I've set up a trigger within the OS
(currently just for Debian) that runs both before and after package
updates. It verifies the signatures in /boot and if they fail before
package updates it creates a log file in
/boot/kexec_package_trigger_pre.txt. If they fail after package updates
run /boot/kexec_package_trigger_post.txt is created. These files contain
the following fields:
CHANGED_FILES: A list of files …
> Add GUI package update handler w/ checksum update function

- initrd/bin/kexec-select-boot
Currently when the boot entries change, kexec-select-boot dies. Given
the normal loop is set up to catch this event and display a regular boot
menu at the next iteration of the loop, instead of dying it would be
better to just warn and then return from that function back into the
main loop. In addition to that I added a GUI menu for the same warning
when in GUI mode.
> Add a gui menu for changed boot entries

- modules/u-root
It will be fixing the u-root build by forcing execution of the go get command into a sequential section of the Makefile not within a recipe.
> Fix u-root parallel build

- initrd/bin/kexec-select-boot
In the event a user does pick the insecure "force" boot option that
bypasses checksum and signing checks in Heads, it would be nice to
provide a clear visual warning during the boot process that they are in
this state. This change will add a kernel argument that changes the boot
console background to be red and removes any boot splash that might
obscure it, in the event the user picks the insecure boot mode.
Since a user should only boot into this mode during emergencies, having
it be apparent that it's an unsafe mode helps ensure the user doesn't
pick this boot option needlessly.
> Add red background to boot console for insecure "force" boot

- initrd/bin/kexec-select-boot
When a user gets confirmation of their boot menu choice, that's largely
to give them the option of making their boot choice the default. In the
case of "force mode" there's no reason for the user to be presented with
that dialog so this change skips right ahead to the boot once they have
> Skip boot choice confirmation in "force" mode

- initrd/bin/kexec-select-boot
- initrd/etc/functions
There was a bug in the "force" boot mode where it would still fail if signatures didn't match. This was because the check_config function validates the signatures for kexec files. I've added a few conditionals
here so that in the case of a forced boot mode, we can bypass those signature checks that would prevent boot and error out to a recovery console.
> Allow insecure boot mode to bypass kexec sig checks

- initrd/bin/gui-init
While the whiptail program wraps text appropriately based on column
size, the fbwhiptail program doesn't, leading to text that scrolls off
the window where it can no longer be read. This change wraps the longer
text output so it all fits.
> Wrap whiptail text that's over 80 characters

- initrd/bin/usb-scan
I'm going through areas of the regular user flow and adding GUI options where there is only text. The USB boot process was missing one so this change adds it.
> Add a whiptail GUI to usb-scan

- initrd/etc/functions
Currently the TPM counter label is hard-coded. By changing it to a
variable in this function we can reuse all of the TPM counter functions
to create other monotonic counters in the TPM (if the hardware supports
it) with custom labels.
> Make TPM counter label a variable

- boards/qemu-coreboot/qemu-coreboot.config
Configure `/dev/sda1` and `/dev/sdb1` for QEMU with coreboot.
> Add boot devices to qemu-coreboot

- initrd/.ash_history
Corrected gpg command needed to generate keys inside of smartcard, fix creation of directory only if not already existing.
An [alternative](https://sorenpoulsen.com/securing-gnupg-keys-on-a-nitrokey-pro) would be to generate keys offline and move the private keys, or only subkeys, to the smartcard, as per user's workflow and smartcard other usages.
> Typo correction in .ash_history

- modules/cryptsetup
This addition permits deployment of customized OEM shipped QubesOS deployments.
The idea behind this is to be able to deploy preinstalled QubesOS trusthworthy machines and permit remote support over them on demand. This is an attempt to relaunch the idea behind [QubesOS librem OEM install disk](https://github.com/marmarek/qubes-installer-qubes-os/tree/r3.2-librem), but this time, including the deployment of a second AdminVM, permitting remote management, by a third party, on demand, through a tor hidden service. This onion hidden service is only available to remote management when both hidden hostname and attached public key are shared, and can be revoked at any time, while the AdminVM needs to be launched to permit remote management as a whole, leaving the user able to bypass and control …
> Adding cryptsetup-reencrypt support. First step into getting OEM predeployed QubesOS machines

- modules/fbwhiptail
The current source URL is not available anymore.
kakaroto changed his copy of heads to point to his own github account's fbwhiptail:
https://github.com/kakaroto/heads/commit/b13cc5e68d9d77ef9bfd6623b812f4205698dafb
But it seems that source.puri.sm/coreboot is a more accessible home for the
project.
> fix the fbwhiptail source URL

- initrd/bin/usb-scan
$TMP_MENU_FILE is an unknown variable. Replaced with /tmp/iso_menu.txt so usb-scan works.
> Fix usb-scan so it proposes found ISOs

- initrd/init
Cherry-pick of @jandryuk to merge atop osresearch/gpg2 branch:
> 
> gpg2 needs GPG_TTY set to function properly.  We set it in /init so it
> is inherited by all children.  The call to $(tty) must be after /dev and
> (preferably) /dev/pts are mounted.
> 
> Signed-off-by: Jason Andryuk <jandryuk@gmail.com>
> Set GPG_TTY before calling gpg in key-init

- blobs/librem_skl/get_blobs.sh
The current links to the ME blob have expired. This updates the links
along with the resulting file names and hashes.
> Update ME repository links/filenames/hashes

- modules/cairo
libtool needs to be patched to not write rpath to targets. `--disable-glib` is also invalid/ignored, so removing.
Closes #484
> cairo: restore build reproducibility 

- boards/x230/x230.config
The bios regions of the 12M coreboot image is 7M: 4M and 3 of the 8M split
image. The rest of the 8M image _generated_ with fake data and not usable
on real systems! It's dangerous to create them and suggest flashing them
externally.
That's exactly why the x230-flash build target is there: To
have a self-contained 4M image and enable easy unlocking of the 8M image
using the _original_ data.
the heads-wiki project is updated accordingly.
Closes #307
Closes #302
> x230: remove 4M and 8M split-images from the build

- initrd/bin/config-gui.sh
- initrd/bin/flash-gui.sh
- initrd/bin/flash.sh
- initrd/bin/generic-init
- initrd/bin/gui-init
- initrd/bin/kexec-boot
- initrd/bin/kexec-iso-init
- initrd/bin/kexec-save-default
- initrd/bin/kexec-seal-key
- initrd/bin/kexec-select-boot
- initrd/bin/kexec-sign-config
- initrd/bin/usb-init
- initrd/bin/usb-scan
- initrd/bin/x230-flash.init
- initrd/etc/functions
- initrd/init
This change adds a config-gui.sh script that provides a GUI to change exported configuration options like you'd see in /etc/config. To protect against any future additions to /etc/config that this would otherwise overwrite, this change adds an additional /etc/config.user file that is intended to be stored in CBFS and at boot combines all /etc/config* files into /tmp/config. Existing scripts have been updated to source this new combined config file.
This script behaves much like on network hardware where the changes apply to the running instance only, and to make them persist you have to explicitly tell Heads to save them, whereby it uses cbfs to add /etc/config.user to the running BIOS and reflash.
> Add GUI to change /etc/config configuration options

- initrd/bin/kexec-seal-key
- initrd/bin/kexec-unseal-key
- initrd/bin/seal-libremkey
- initrd/bin/seal-totp
- initrd/bin/unseal-hotp
- initrd/bin/unseal-totp
- initrd/etc/functions
Replacing rm with shred for secrets that should not be present in ram when booting OS.
Address the following [concerns](https://github.com/osresearch/heads/pull/511#issuecomment-464363619)
> Use shred instead of rm on secret related files.

- modules/dropbear
- modules/make
- modules/popt
- modules/zlib
The new URL automatically redirects to a nearby, current GNU mirror.
Also, the fact that it's HTTPS helps with restrictive outbound firewall policies that disallow plaintext traffic (for example, using Qubes' firewall functionality).
> Improve mirror URLs

- blobs/librem_kbl/get_blobs.sh
- blobs/librem_skl/get_blobs.sh
Rather than download large repositories of files from sources we
don't control and patch files as needed, simply extract the
files from precompiled, known good Purism coreboot images.
This offers multiple advantages:
- single source for all blobs, which we control
- significantly smaller download requirements for end user
- significantly less script complexity
- much, much faster
> get_blobs: extract blobs from precompiled Purism coreboot images

- initrd/bin/flash-gui.sh
The notion of "cleaned" vs. "non-cleaned" ROM is only relevant to people
who are developing Heads. This change gives a better explanation of the
difference between the two options, so the user can make the appropriate
choice.
> Improve flash GUI documentation

- initrd/bin/config-gui.sh
- initrd/bin/mount-usb
Currently Heads relies on a hard-coded config value to determine which
USB disk to mount. This can be problematic when trying to distribute a
pre-built version of Heads that can work on multiple disk
configurations. I've modified the USB mounting script so that it
attempts to detect all USB boot disks present on the system, pick sane
defaults, and prompt the user when there are multiple choices.
I've also removed the USB configuration option from config-gui.sh as
this config option is no longer used.
> Detect USB disk dynamically

- modules/pinentry
TODO: remove all unneeded config options for ALL modules
Fixes #552
> Fedora 30 fix for pinentry: remove gtk and gnome3 support. 

- initrd/bin/gpg-gui.sh
This change updates the very basic GPG smartcard feature in the GPG GUI
so that it can properly support generating a key from within Heads. It
offers the user the option to copy the generated GPG public key to a USB
thumb drive so it's not lost as well as the option to reflash the
current Heads BIOS with this new public key added to the keyring.
I've moved the common functions required to flash a new ROM with GPG
changes into a shared function at the top of the script.
> Add GPG smartcard keygen feature

- initrd/bin/kexec-parse-bls
- initrd/bin/kexec-select-boot
Have made this fix more conservative. If kexec-parse-boot provides any output at all, then the BLS parsing will not be performed. The /boot/loader/entries directory will only be parsed if there are no grub .cfg files with direct kernel parameters within them.
To proceed to execute kexec-parse-bls, there are two tests: 
```
[ ! -s $option_file ] - $option_file is zero size
[ -d "$bootdir/loader/entries" ] - /boot/loader/entries directory exists
```
I've tested this with Fedora 30, Qubes 4.0.1 (which seems to have a bizarre /boot/loader/entries directory...) and for good measure, Ubuntu 19.04
> Parse grub config files for Fedora 29/30

- Makefile
Right now all git submodules are left behind on a git clone. Add
git submodule update --init --checkout according to the docs, see
https://www.coreboot.org/Build_HOWTO
> Makefile: add submodule checkout after git cloning coreboot

- initrd/bin/gui-init
Clean up the main menu to only include menu entries that are expected
to be part of users' everyday routines. On the main menu itself, each option
should be almost trivially easy to understand.
* move "Exit to recovery shell" under Advanced Settings (quite obvious change IMO)
* add "Refresh TOTP/HOTP". Needed by anybody who verifies firmware integrity using TOTP
* keep "Advanced Settings" for the other stuff most people won't care too much about, but rename to "Settings" only. (we don't have "normal" ones, so why have "advanced" ones, right?)
* add "Power Off" at the bottom. IMO this is can be very useful to anybody: This enables users to
only verify the firmware integrity using OTP, and do nothing more. After having left the device out of sight, one might want to do a quick sanity check …
> gui-init: reorder, simplify main menu entries and add Power Off entry

- initrd/bin/seal-libremkey
- patches/libremkey-hotp-verification.patch
Fix two issues with HOTP generation/validation:
- truncation of the HOTP secret when passing to libremkey-hotp-verification
- fix validation of Librem Key admin pin when passphrase with spaces is used
> HOTP fixes

- initrd/bin/config-gui.sh
- initrd/bin/flash.sh
- initrd/bin/gpg-gui.sh
- initrd/bin/gui-init
- initrd/bin/kexec-select-boot
- initrd/etc/functions
series of small tweaks to the HEADS UI which improve user experience:
* add ability to directly access menu options in config-gui via function parameter
* filter out invalid boot devices from options menu
* don't reboot after creating new HOTP/TOTP
* jump directly to boot device selection when existing is invalid
* add Full Reset config option to reset TPM, GPG, boot signatures
* check for file existence when persisting between flashes
* default to Y when selecting a new boot device
* prompt for retry when GPG card detection fails
* better handle user cancellation when adding a new key to ROM
* persist device serial in CBFS between flashes
> UX Tweaks [2/2]

- initrd/bin/gpg-gui.sh
- initrd/bin/gui-init
- initrd/bin/oem-factory-reset
- initrd/etc/functions
Add an improved OEM Factory reset function, which erases/resets the TPM and GPG security token, generates a new GPG key, signs the files in /boot and sets the default boot device / boot selection.
Add a new item in the main options menu for it, and remove the existing GPG reset function since it is superseded by this.
Add a function to detect a clean boot situation, and prompt the user to run the OEM factory reset.
> OEM factory reset

- initrd/bin/gui-init
Update text on TOTP error prompt to provide better guidance for users
following the use of the OEM factory reset function
> gui-init: update TOTP error prompt

- initrd/bin/unseal-hotp
If /boot isn't mounted, we can't read the HOTP counter, so no point in reading from the TPM.
This speeds up getting to the main menu in the case of an inaccessible or non-existent /boot.
> unseal-hotp: ensure /boot mounted before checking HOTP secret

- initrd/bin/oem-factory-reset
Since the custom password is used to set the GPG admin
password as well as the TPM and GPG user passwords, an
8-character minimum is required. Inform the user of this,
and validate custom password length upon entry.
> oem-factory-reset: enforce 8-char min on custom password

- Makefile
- modules/coreboot
- modules/msrtools
- modules/musl-cross
- modules/tpmtotp
- patches/musl-cross-81d563e.patch
These were the only three that were being pulled from git heads rather than specific tags or releases.
Also changes the top level `Makefile` extraction of tarballs to use `--strip 1`, which ensures that the extracted directory matches the name in `$($(MODULE)-dir)`.
> Pin tag of musl-cross, tpmtotp and msrtools

- modules/lvm2
- patches/lvm2-2.02.168.patch
Something must have changed in the musl stdio buffering code; lvm is doing lots of weirdness with streams that seems to be causing the segfault and because they have closed stdout/stderr, it was hard to track down why it was happening.
> lvm2: turn off buffering, which prevents segfault with new musl (#651)

- initrd/init
busyboy tty isn't working after the musl-cross-make change so
revert to known good value.
> init: fix invalid GPG_TTY variable

- modules/libremkey-hotp-verification
- patches/libremkey-hotp-verification.patch
Pass through new toolchain path via $(CROSS) so we can set the
c/c++ compiler paths correctly for CMake. Adjust patch to use
new paths, and fix compiler/linker paths to correct a libusb linking issue.
This fixes compilation of the libremkey-hotp-verification module, which was broken
when toolchain was changed to musl-cross-make in commit 791d064.
CMake isn't my forte, so open to "better" solutions.
Fix derived from: https://stackoverflow.com/questions/36195791/
> libremkey-hotp-verification: toolchain adjustments

- initrd/bin/flash-gui.sh
Not setting USB_FAILED when call to mount-usb succeeds results
in a spurious 'sh: 0 unknown operand' error printed to console.
> flash-gui: set unset variable USB_FAILED

- initrd/bin/gui-init
- initrd/init
Some (out of tree) servers require use of a USB keyboard, and need
the USB kernel modules loaded prior to checking for keypress to enter
a recovery console. Since loading the modules affects the value in PRC5
and can cause issues putting a LUKS key in TPM, guard the loading of the
USB modules with CONFIG_USB_KEYBOARD and remove the unguarded call from
gui-init.
This should resolve issues #603 and #674.
> init: load usb modules for devices using USB keyboard

- initrd/bin/gui-init
Commit 6b5adcca moved the call to enable_usb from gui-init
to init and guarded it with CONFIG_USB_KEYBOARD, but it was
missed that this is needed for the clean boot check logic
when a librem key is used. Add the call back to gui-init
and guard it properly
Test: clean_boot_detect works properly on a librem 13v4
> gui-init: fix checking librem key card-status

- initrd/bin/oem-factory-reset
fix $GPG_GEN_KEY getting clobbered when using a custom password
> oem-factory-reset: fix GPG key backup filename

- patches/coreboot-4.8.1/0060-buildgcc-acpica-unix2-url-change.patch
acpica-unix2 cannot be downloaded per www.acpica.org since cert is signed by Intel which cert authority is unknown from older build systems... Cert was renewed March 10 2020. URL changed to crux.ster.zone
fixes #695 
Problem without fix can be observed [here](https://app.circleci.com/pipelines/github/tlaurion/heads/28/workflows/84a5871c-2234-4aba-a42e-e5d2b8a60924) and [here](https://gitlab.com/tlaurion/heads/-/jobs/472309064) in [public CIs]([url](https://github.com/osresearch/heads/issues/571)) ([if they were available](https://github.com/osresearch/heads/issues/571)) since March 10, users cannot build Heads since that day. Manual browser navigation over https://www.acpica.org and cert manual validation shows the problem.
> coreboot-4.8.1 : fix acpica-unix2 download

- boards/qemu-coreboot/qemu-coreboot.config
- config/coreboot-qemu.config
Now useful to debug something through make BOARD=qemu-coreboot.
TODO: [map a virtual TPM instance ](https://github.com/osresearch/heads/issues/516#issuecomment-538776741) and USB passthrough. 
Thanks to @orangecms for the tip. If you have others regarding https://github.com/osresearch/heads/issues/516#issuecomment-492695279, you are more then welcome.
Fixes #516 #701 and #158 
Based on top of #706 (should be merged first)
With testing happening on #700, another pull request will bonify he debugging output of this board too since debugfs will be useful through /etc/fstab presence.
> qemu-coreboot: finally a useable debug/test board

- .circleci/config.yml
- Provide logs.tar.gz and cpios to facilitate debugging of reproducibility issues
- Provide x230-flash.rom to be able to externally flash heads for newcomers to heads along with coreboot.rom which is to be internally flashable, untouching ME Gbe and other things (unmodified CBFS in coreboot)
- Delete build/make directory in CI, else there is issues when host's make binary versions mismatches, which is a fix for older host build systems (ubuntu 16.04 original CI of @osresearch which hides cross-make-gcc onto docker dependency for which we don't know what exactly was put in the host build dystem docker image to produce actual results.)
This is a first step toward https://github.com/osresearch/heads/issues/571
> CIs: pass CircleCI to debian:bullseye docker image

- modules/libremkey-hotp-verification
Make hotp-verification build reproducible on Heads.
Move from CMake to GNU Make
Change hotp-verification version to one supporting Makefile build
Use local libusb
Connected:
- https://github.com/Nitrokey/nitrokey-hotp-verification/issues/13
- #722
> Make hotp-verification build reproducible across CIs

- modules/gpg2
- modules/libassuan
- modules/libgcrypt
- modules/libgpg-error
- modules/libksba
- modules/npth
- modules/pinentry
- Remove unrecognized configure options
- fixes gawk issue #668 by upgrading to libgpg-error 1.37 instead of patching 1.32 for regex change (fixed upstream)
- move patches so they match new versions for libassuan, gpg and libgcrypt (no change)
Version change:
- gpg 2.2.10 -> 2.2.20
- libassuan 2.5.1 -> 2.5.3
- libgcrypt 1.8.3 -> 1.8.5
- libgpg-error 1.32 -> 1.37
Size changes:
- gpg                   886.5 -> 911.3 kB
- gpg-agent:            371.9 -> 376.0 kB
- scdaemon:             399.5 -> 407.8 kB
- libgpg-error.so.0     125.9 -> 130.0 kB
Unrecognized options on gpg2 toolstack:
- disable-nls and disable-asm disable-keyserver-helpers disable-hkp disable-finger disable-dns-srv disable-dns-cert and disable-wks-server
(Sorry. This is a exact redo of …
> upgrade gpg toolstack to latest versions

- initrd/bin/network-init-recovery
- Adds the missing piece so IP is requested from DHCP if IP not defined in board
- Then sync time from DNS server provided by DHCP prior of attempting sync from pool.ntp.org
> network-init-recovery script: Request IP from DHCP, NTP time

- .gitlab-ci.yml
Upstream is Fedora-32 which is not compiling correctly with coreboot. Didn't trouleshoot.
> Add Fedora 30 gitlab-ci CI configuration building x230-hotp-verification

- .circleci/config.yml
- .gitlab-ci.yml
Both CircleCI and GitlabCI will now depend on `heads-username` tuple to build a reusable cache from the CI that launches the builds.
This will permit PRs to be built faster for an established CI.
Notes:
- GitlabCI permits to invalidate the cache from GUI directly from a failing pipeline.
- CircleCI requires to change a environment variable from the envirnment variable GUI. In case a build needs to have its cache flushed out, the project owner on a CI needs to change `CACHE_VERSION` to something new and restart the build.
> CIs: Replace cache fingerprints so cache is reusable between builds

- .circleci/config.yml
- .gitlab-ci.yml
Previous commit didn't save cache with `.Environment.CIRCLE_USERNAME`. This does.
> CircleCI: fix save_cache

- initrd/bin/oem-factory-reset
It is already possible to change the default user and admin/TPM PIN during OEM factory reset. It would be nice to also be able to choose a proper name, mail and comment field for the GnuPG keys.
> Add option to choose GnuPG userinfo during OEM reset

- initrd/bin/mount-usb
Provide user some info as to what is heppening, otherwise the
system appears to be hung for 5s with no indication why.
Side note: do we really need a 5s delay after this?
> mount-usb: provide useful output when loading kernel modules

- initrd/bin/gui-init
- initrd/init
Show RAM in GB, since the calculation in MB is imprecise as
it excludes RAM allocated for GPU (eg).
Fix display of firmware version strings which contain spaces by
adjusting cut and simply chopping off the date at the end, which
is a fixed 10-char length.
> gui-init: Fix RAM and firmware version strings

- modules/gpg2
- modules/libassuan
- modules/libgcrypt
- modules/libgpg-error
- modules/libksba
- modules/npth
- modules/pinentry
This reverts commit 972c25de7df9cf797fd211bc795fe057462a6432.
This commit broke OEM factory reset functionality, so revert it
until the issue can be properly diagnosed.
Addresses issue #764
> Revert "upgrade gpg toolstack to latest versions"

- initrd/bin/mount-usb
This helps people to differentiate their USB drives, if they have multiple devices inserted (e.g. Nitrokey Storage + USB drive).
> Add partition Label to list of mount-usb

- initrd/bin/seal-hotpkey
With current implementation, Librem Keys with VID 0x316d are
not identified properly; correct the if/else logic to resolve.
> seal-hotp: Fix HOTP key identification

- modules/hotp-verification
modules/hotp-verification: update to upstream master
Update hotp-verification to Nitrokey upstream commit 03a198c4.
Test: build/boot Librem 13v4, verify Librem key verification functional.
> modules/hotp-verification: update to upstream master

- patches/hotp-verification-03a198c418a60c54ef3ec67ea8a9a2d29b675b9b.patch
Commit 7ea13ee0 made some significant changes to Librem/Nitrokey
verification which broke both compilation and calls to hotp_initialize.
Fix them via a patch until it's fixed upstream.
> patches: Add patch to fix hotp-verification

- initrd/bin/gui-init
- initrd/bin/oem-factory-reset
- initrd/etc/functions
For the handful of operations which need to be done with /boot
as the pwd, encapsulate them in subshells to ensure the pwd
doesn't unexpectedly change for other operations, as functions
which need to mount/unmount /boot may fail if the pwd isn't root.
Also, set the pwd to root at the start of detect_boot_device as an
added safety measure.
Test: run oem-factory-reset function, ensure it doesn't fail to
detect boot device due to incorrect working directory.
> Encapsulate changes to working directory inside subshells

- initrd/bin/kexec-select-boot
- initrd/bin/oem-factory-reset
Handful of small fixes to address bugs in oem-factory-reset and kexec-select-boot which manifested with an install of Fedora 32:
* oem-factory-reset needs to parse BLS spec grub files as well as standard ones
* oem-factory-reset needs to set the index of kexec_default.{i}.txt rather than always using 1
* oem-factory-reset and kexec-select-boot should use -s vs -r to test if any valid boot entries produced by kexec-parse-boot
> Fix OEM factory reset and setting of default boot with F32

- patches/kexec-2.0.20.patch
This patch was reported by @bemoody in issue #699
Tested via `BOARD=x230-hotp-verification` on a Thinkpad x230
> Fix kexec to work with Debian Installer (fixes #699)

- initrd/bin/gui-init
Attempting to reset the TPM when once isn't present causes a kernel
panic, so let's not allow users to do that.
Test: verify 'No TPM Detected' shown on Librem Mini when Reset TPM
option selected from menu.
> gui-init: Guard TPM reset function with CONFIG_TPM

- initrd/bin/config-gui.sh
- initrd/bin/gui-init
- initrd/etc/functions
* remove double-prompt for checksum update
* Fix eval of DEV_NUM_PARTITIONS on empty drives
* Improve handling of boot device selection in config_gui
> GUI / Boot Device Tweaks

- .circleci/config.yml
This changes the way CircleCI handles cache and limit the possibility of cache corruptions and removes the CircleCI owner bounding that was there previously.
Now:
- If modules/* and patches/* have the same hashes, that cache is restored. It saves the new cache if the hashes are different. This cache is usefull for most changes happening in Heads, which are security policy related and linked to scripts changes. If modules or hashes changes and no cache exists, if will restore the next cache.
- If musl-cross module and applied patches have the same hashes of an existing cache, that cache is restored. It is saved once for a single hash which means that the module version (commit) and applied patches are the same. This permits to economize one hour of build time for each build and rarely ever …
> CircleCI : specialized caches

- patches/coreboot-4.8.1/0000-measuredboot.patch
- patches/coreboot-4.8.1/0009-Add-heads-TPM-measurements-to-Skylake-Kabylake.patch
- patches/coreboot-4.8.1/0030-sandybridge.patch
As part of migration to coreboot 4.12, which includes measured boot
without additional patches, measure all parts of the firmware and the
payload into PCR2.
The same is done in coreboot 4.12. This commit ensures that boards not
migrated yet will show the same behaviour.
TODO: Update heads-wiki.
Signed-off-by: Patrick Rudolph <patrick.rudolph@9elements.com>
> patches/coreboot-4.8.1: Measure firmware into PCR2

- .circleci/config.yml
removes build/make directory, else patches are reapplied on top of already existing directory causing builds to fail.
> CircleCI: mitigate issue #799

- modules/coreboot
Update Heads to allow building with coreboot 4.12:
* update version and hashes for coreboot and coreboot-blobs
* use coreboot's own toolchain (adapted from #709)
Build/boot tested on Librem 13v2/13v4/15v3/15v4, x230, qemu-coreboot-fbwhiptail 
Outstanding issues:
* Qubes/Xen fails to boot on SKL/KBL Librems (fine on x230 and out of tree WHL-based Librem Mini)
* Individual boards can be migrated to coreboot 4.12 in subsequent PRs
> Add option to build against coreboot 4.12

- .circleci/config.yml
- Makefile
- modules/coreboot
- Fix issue #807
- Esthetical modules/coreboot changes to facilitate future coreboot maintainership putting hashes of coreboot and coreboot-blobs together
- Fix #799 with implementation of @osresearch's recommendation.
@MrChromebox : please review
> Fix CircleCI build problems

- initrd/bin/kexec-parse-bls
- initrd/bin/kexec-parse-boot
Some grub configs/bls entries contain the full paths to the
kernel/initrd files, which the parsers currently fail to handle,
causing a failed boot without any useful error being presented to the user.
To fix this, strip the bootdir prefix from the menu entries when parsing,
should it exist.
Test: build/boot Librem 13v2 w/F32 and bls entries containing mixed relative and 
absolute paths for kernel/initrd
> kexec-parse-boot/bls: Strip boot dir from front of grub entries

- .circleci/config.yml
Might need to go more in detail, but sufficient for now. Builds successfully.
> CircleCI: bring recent failing logs on CI output

- .circleci/config.yml
Coreboot 4.12, on which the librem_mini depends, doesn't build under debian:10 docker image as of right now.
It was building over debian:bullseye (where 4.8.1 boards didn't) which constructed a valid cache that
was reused when building #806 (https://app.circleci.com/pipelines/github/tlaurion/heads/364/workflows/df9bad8d-8ff1-40da-b8d8-1b87a05be509/jobs/392)
Consequently, more troubleshooting would need to be done under local debian:10 docker image.
> CircleCI: removing librem_mini board under CircleCI

- blobs/t420/extract.sh
- blobs/x220/extract.sh
Command returns a list of utilities found. This can happen if multiple
coreboot folders are present.
Use only one to fix a crash in the following lines.
Test: Being able to extract blobs when two coreboot folders are present,
both containing an IFDTOOL.
Signed-off-by: Patrick Rudolph <patrick.rudolph@9elements.com>
> blobs/x220|t420: Fix extract script

- initrd/bin/kexec-save-default
Changing the default boot was failing because remove the old entries did
not work as `rm "/some/path/*.txt"` does not work as intended, e.g. the
asterisk is no catch-all.
> Remove quotes to fix use of asterisk in command

- modules/flashtools
- [cbfs: fix addition of zero-length files ](https://github.com/osresearch/flashtools/commit/40d5170e84a3822552df7a500cd00aa870fdfe76)
Successful [here](https://app.circleci.com/pipelines/github/tlaurion/heads/371/workflows/d76e142a-9c37-4f37-b291-a40db9c5b825/jobs/400)
@MrChromebox ?
> modules/flashtools: bring par to upstream flashtools.

- initrd/etc/functions
Currently, exiting the recovery shell results in a kernel panic,
necessitating a hard reset / power cycle. As this is less than ideal,
drop the exec and add a loop to restart the shell.
Addresses issue #833
Tested under qemu-coreboot-fbwhiptail
> functions/recovery: loop recovery shell when exited

- .circleci/config.yml
- Makefile
- modules/coreboot
- modules/linuxboot
This is a nifty way permitting us to limit ressource allocation if desired (CIs).
From experiementations, there is no way to limit ressource consumption on CircleCI but to pay to have more resources.
In our use case, with cache now being built when boards builds successfully for the same modules/* and patches/* hashes, a cache is built. It fallsback to taking the last available built cache for musl-cross-make having been built for its own specific module signature and existing patches.
The problem we had recently in CI was linked to the addition of coreboot 4.12 board (librem_mini-NoTPM) which, for some obscure reason, failed building with OOM being invoked. GCC expects each thread to have 1GB available, and CircleCI's guaranteed resource allocation is of 4Gb ram, with 32 softcores. So …
> Add 'CPUS' as make BOARD=X argument

- .circleci/config.yml
- boards/librem_mini/librem_mini.config
- config/coreboot-librem_mini.config
There's only one Librem Mini board, it doesn't use a TPM,
no reason to unnecesarily lengthen the board name.
> librem_mini-NoTPM: drop '-noTPM' suffix

- config/coreboot-librem_mini.config
- modules/coreboot
- patches/coreboot-4.12/0010-cross-compiler-support.patch
- add coreboot-4.12 cross-compiler support patch
- adjust coreboot module to use musl-cross-make to build
- set librem_mini to use CONFIG_ANY_TOOLCHAIN
built on top of #843 since that's a quick/easy merge
> coreboot-4.12: Use musl-cross-make

- modules/fbwhiptail
Even though repo is stable at the moment, improves reproducibility.
> fbwhiptail: Fix module to specific git commit vs master

- initrd/bin/kexec-save-default
- initrd/bin/kexec-save-key
- initrd/bin/kexec-sign-config
- initrd/etc/functions
Update_checksum was already changing files in /boot, before checking for
gpg card. If no card is present, the user will end up in the recovery
next time instead of getting the same dialog again. Therefore, the
confirm_gpg_card should be checked before altering files.
The dead -u flag/$update_counter is used to mark the necessity to
update the hash files now.
Maybe it would be nice to have a dialog explaining what's happening [here](https://github.com/osresearch/heads/blob/92e9a24902a34c4a1fa68753ec1f2500a277d9f1/initrd/etc/functions#L227) anyway? (this was the place, where you got stuck without this PR)
> Change hash files only if gpg card is present

- config/coreboot-librem_15v4.config
Set the kernel video mode for the internal display to 1080p,
as the native panel resolution of 2160p is difficult to read.
A recent update to fbwhiptail allows the GUI to make use of the
scaled resolution as well, provided it is set via kernel param.
> config/coreboot-librem_15v4: set kernel video mode to 1080p

- config/coreboot-librem_mini.config
- modules/purism-blobs
Increase size of CBFS to 0xC00000 (from 0x800000) to accomodate
newer/larger kernels.
Update purism-blobs module so an update/modified IFD and smaller
ME blob are used.
> Librem Mini: increase size of CBFS

- .circleci/config.yml
- modules/gpg2
- modules/libassuan
- modules/libgcrypt
- modules/libgpg-error
- modules/libksba
- modules/npth
- modules/pinentry
- patches/gpg2-2.2.21.patch
- patches/libassuan-2.5.3.patch
- patches/libgcrypt-1.8.6.patch
- patches/libksba-1.4.0.patch
It builds for all boards but cannot be injected for librem_mini: https://app.circleci.com/pipelines/github/tlaurion/heads/524/workflows/1605502b-5125-40de-8896-05a5d69086a5/jobs/568
```
librem_mini/util/cbfstool/cbfstool librem_mini/coreboot.pre.tmp add-payload -f ../../build/librem_mini/bzImage -n fallback/payload  -c none  -r COREBOOT   -C "intel_iommu=igfx_off quiet loglevel=2" -I "../../build/librem_mini/initrd.cpio.xz"
E: Could not add [../../build/librem_mini/bzImage, 7154226 bytes (6986 KB)@0x0]; too big?
E: Failed to add '../../build/librem_mini/bzImage' into ROM image.
E: Failed while operating on 'COREBOOT' region!
E: The image will be left unmodified.
make[1]: *** [Makefile.inc:1020: librem_mini/coreboot.pre] Error 1
rm librem_mini/util/cbfstool/fmd_parser.c …
```
> WiP: gpg2 2.21 LTS upgrade (gnupg toolstack)

- initrd/bin/gui-init
- initrd/bin/oem-factory-reset
In gui-init, check for presence of CONFIG_BOOT_DEV, and if missing or unable to be mounted, present the user with a menu offering the option to select another disk, boot from USB, continue to main menu, or drop to a recovery shell.
In oem-factory-reset, if an installed OS is not detected, then skip setting the default boot device or generating /boot checksums.
These changes facilitate ease of use for users when installing a new/empty boot disk, or for delivering an OEM system with preconfigured keys but no installed OS.
> Improve handling of missing or empty boot disk

- .circleci/config.yml
bonus: qemu-coreboot-fbwhiptail board addition
Successful build log here: https://app.circleci.com/pipelines/github/tlaurion/heads/583/workflows/fe4eec40-336b-4fbf-bd50-e8708413d290/jobs/631
Waiting for failed log output from [here](https://app.circleci.com/pipelines/github/tlaurion/heads/585/workflows/09675c1e-f358-4c35-bc39-87b2befc63cb/jobs/633)
EDIT: good to merge @MrChromebox if you have tweaks: point here is to only show detailed logs failing when there is a fail without polluting main build output (so we know what failed without searching for "<==" as before.
> CircleCI seperation of main failed error and detailed logs of last minute

- initrd/bin/kexec-sign-config
The -u arg does not take a parameter, so remove the trailing colon.
Fixes /boot hashes not being updated when update_checksums() is called.
> kexec-sign-config: fix args to `getopts`

- boards/librem_13v2/librem_13v2.config
- boards/librem_13v4/librem_13v4.config
- boards/librem_15v3/librem_15v3.config
- boards/librem_15v4/librem_15v4.config
- boards/librem_mini/librem_mini.config
- initrd/bin/gui-init
And enable it for all Librem boards.
On first time through gui-init loop, if CONFIG_AUTO_BOOT_TIMEOUT exists and is set, and if HOTP validation was successful, then attempt to boot the default target after CONFIG_AUTO_BOOT_TIMEOUT seconds if not interrupted by key press.
Set CONFIG_AUTO_BOOT_TIMEOUT to 5s for all Librem boards.
> Add option to auto-boot default target on successful HOTP verification

- boards/t430-hotp-maximized/t430-hotp-maximized.config
- boards/t430-maximized/t430-maximized.config
- boards/x230-hotp-maximized/x230-hotp-maximized.config
- boards/x230-maximized/x230-maximized.config
Misses some typos correction under #912 under comments.
> xx30-*-maximized boards: typo fix in comments expend -> expand

- modules/coreboot
building `BOARD=qemu-linuxboot` fails due to an error in `modules/coreboot` (which is not used for LinuxBoot builds)
> non-coreboot-builds: do not error if CONFIG_COREBOOT_VERSION is not set

- initrd/bin/oem-factory-reset
> Default to 4096 bit for OEM factory reset (fixes #831)

- config/coreboot-t420-hotp-maximized.config
- config/coreboot-x220-hotp-maximized.config
Sorry about that. Would have swore that CI was successful prior of merging https://github.com/osresearch/heads/commit/0f1f547eb13ebe90a5fe68f3637db9ab7ec43df0
- Missed correcting the paths to initrd since copied from xx20-maximized boards config.
> xx20-hotp-maximized: forgot to fix path to initrd, failed under CI.

- modules/linuxboot
On a clean checkout of HEADS when attempting to build the `qemu-linuxboot` board, configuration of Linuxboot fails:
```
Pre-building edk2 OVMF
Initializing workspace
/home/docker/workspace/heads/build/linuxboot-git/edk2/BaseTools
Loading previous configuration from /home/docker/workspace/heads/build/linuxboot-git/edk2/Conf/BuildEnv.sh
WORKSPACE: /home/docker/workspace/heads/build/linuxboot-git/edk2
EDK_TOOLS_PATH: /home/docker/workspace/heads/build/linuxboot-git/edk2/BaseTools
CONF_PATH: /home/docker/workspace/heads/build/linuxboot-git/edk2/Conf
using prebuilt tools
Running edk2 build for OvmfPkgX64
Usage: build.exe [options] [all|fds|genc|genmake|clean|cleanall|cleanlib|modules|libraries|run]
build.exe: error: option -n: invalid integer value: 'PUS'
```
Changing `$$CPUS` to `$(CPUS)` in …
> linuxboot: Pass $CPUS to edk2/OvmfPkg/build.sh unerroneously

- modules/coreboot
Similar to #940, `$$CPUS` needs to be changed to `$(CPUS)` in `modules/coreboot` for consistency.
> coreboot: Pass $CPUS to coreboot make target unerroneously

- config/busybox.config
Disabling the latter to have successfull build otherwise [fails](https://app.circleci.com/pipelines/github/osresearch/heads/269/workflows/48be189a-953a-4829-b6f4-0fbb76d3fb7d/jobs/295).
@Thrilleratplay amendment to https://github.com/osresearch/heads/commit/69eb81995809faee342c35b3916fdfea95a8aa4f
> busybox: CONFIG_BASH_IS_ASH is incompatible with CONFIG_BASH_IS_NONE

- initrd/bin/oem-factory-reset
> oem-factory-reset: set default KEY_LENGTH to 3072 and change expectation management message to console

- .circleci/config.yml
- modules/coreboot
- patches/coreboot-4.11/0080-util-crossgcc-builgcc_temp_fix_from_https_to_http.patch
- patches/coreboot-4.13/0080-util-crossgcc-builgcc_temp_fix_from_https_to_http.patch
- patches/coreboot-4.8.1/0080-util-crossgcc-builgcc_temp_fix_from_https_to_http.patch
The idea here is a cache to restore from (musl-cross from coreboot version bound crosscomipler, from which coreboot is built)
1- Reuse existing cache for all modules and patches created digest's hash. (If a single module or patch changes, we have cache miss)
2- Reuse existing coreboot and musl-cross-make created digest's hash (If a patch was added to current coreboot, or new coreboot version was added in coreboot module definition, we have a cache miss. Otherwise, we reuse the whole musl-cross-make and coreboot cache for current used versions.)
3- Reuse existing musl-cross-make created digest's hash matching cache (If musl-cross-make module didn't change, we don't rebuild it)
Per https://github.com/osresearch/heads/pull/947#issuecomment-753507412 proposition
@Tonux599 please challenge me!
> CircleCI: Add coreboot+musl-cross cache

- boards/t430-flash/t430-flash.config
- boards/x230-flash/x230-flash.config
Produces only a 4mb top rom following actual name standard as other boards.
Fixes #951 (not so elegant. If you have better idea, please advise)
> xx30-flash boards: produce top.rom and remove 12mb rom for clarity

- modules/flashrom
Allows KGPE-D16 users to flash the BMC internally.
@MrChromebox please review also as makes modifications to your work. As laid out in the commit messages:
> * Flashrom was being fetched with git and was always using `master`
> * No patches were being applied (i.e. `0100-enable-kgpe-d16.patch` was being ignored).
> Kgpe d16 flashrom fix

- modules/hotp-verification
Update nitrokey-hotp-verification to upstream master, which
pulls in 2 changes:
- update OTP secret length from 20 bytes to 40 bytes
- fixes handling for branding strings containing spaces
Test: build/boot Librem 13v4, verify LK verification working
> modules/hotp-verification: Update module to latest version

- modules/libusb
[Last CI build in master fails because of a 302 temporary redirect resulting to bad checksum](https://app.circleci.com/pipelines/github/osresearch/heads/277/workflows/1748498a-fe5e-4bb6-a12e-e334f8f76f1b/jobs/305):
```
2021-02-03 00:41:30+00:00 WGET https://downloads.sourceforge.net/project/libusb/libusb-1.0/libusb-1.0.21/libusb-1.0.21.tar.bz2
if ! wget -O "/root/project/packages/libusb-1.0.21.tar.bz2.tmp" https://downloads.sourceforge.net/project/libusb/libusb-1.0/libusb-1.0.21/libusb-1.0.21.tar.bz2 ; then exit 1 ; fi ; mv "/root/project/packages/libusb-1.0.21.tar.bz2.tmp" "/root/project/packages/libusb-1.0.21.tar.bz2" 
--2021-02-03 00:41:30--  https://downloads.sourceforge.net/project/libusb/libusb-1.0/libusb-1.0.21/libusb-1.0.21.tar.bz2
Resolving downloads.sourceforge.net …
```
> libusb: replace package origin from sourceforge to github release

- .circleci/config.yml
Dodging the problem of CircleCI limiting builds to 5h by putting CPUS=24 in CircleCI config.
Interim fix to #970, which goal is to parallelize builds.
> Circle ci optimization build time

- .circleci/config.yml
As per the commit message:
> * Bump CircleCI config version to 2.1.
> * Use commands and parameters to get rid of repeated commands. New boards can be added with just 5 lines at the bottom of the config.
> * Made use of some parallelisation. Currently a single board from each Coreboot version is built. Afterwards all remaining boards are built in parallel.
Successful build [here](https://app.circleci.com/pipelines/github/Tonux599/heads/93/workflows/a00e08d4-d94f-4d11-9617-64856f8ef1d3)
Currently rebuilding [here](https://app.circleci.com/pipelines/github/Tonux599/heads/93/workflows/06778106-3ed4-44df-9674-9300d2d54371) to test cache is working. (Edit: works) 
A few things to note here:
- As long as a single job does not exceed the 5hr limit, the CI can run for however long it needs to. So …
> CircleCI: Overhaul with parallelisation and parameters for a cleaner config

- blobs/xx20/download_parse_me.sh
- blobs/xx30/download_clean_me.sh
Incorrect parentheses brackets used in those scripts meant that the script as a whole did not return the correct exit code. The use of `( )` brackets created a sub-shell to which the exit code applied to that sub-shell. Changing to `{ }` does not create a sub-shell and as such, the script will return its true return code.
This is evident by changing a character of `FINAL_ME_BIN_SHA256SUM` in `./blobs/xx20/download_parse_me.sh` and running `./download_parse_me.sh && echo "Okay" || echo "Failed"`.
It is important that the exit codes are correct as we want to catch errors as early as possible in CI builds.
> Fix exit codes for ME download scripts

- Makefile
So that cryptsetup2 binaries are copied under tools.cpio when building initrd so that cryptsetup2 defined under board configs is available inside of Heads.
@MrChromebox please review
> Makefile: Add cryptsetup2 missing statement into Makefile

- initrd/init
The banner sent to tty0 is sent both local and remote in past tests.
@MrChromebox please approve.
> init: remove double heads motd banner, keeping the one sent to tty0 

- initrd/bin/flash-gui.sh
- initrd/bin/gpg-gui.sh
- initrd/bin/kexec-select-boot
NEWT as opposed to FBWhiptail enforces line width.
So if input is of different sizes, we have a chance that the lines are wrapped over multiple lines.
This is preventively fixing this by increasing such lines from 60 chars to 90.
@MrChromebox sorry for not having proactively added this in previous accepted pull request.
> Newt width size additional fixes

- initrd/bin/gui-init
When files in /boot fail hash verification, the list of files
can sometimes overflow the whiptail msgbox, preventing the
prompt and buttons to update checksums from showing. To mitigate
this, if # of files is > 10, use less to show the file list and
present a separate prompt to update the checksums once the file
list has been viewed.
Addresses issue #1048
> gui-init: Handle overflow of list of files w/failed hashes

- initrd/bin/flash.sh
Show progress of flashrom reads/writes when flashing by means
of a progress bar, adapted from the Librem coreboot flashing script.
Also provides a time-stamped flashrom log in /tmp to aid diagnosis in the
event that a firmware update fails.
> flash.sh: Add progress bar

- initrd/init
Background colors were broken since $CONFIG_FBWHIPTAIL and $CONFIG_NEWT are defined under board configs as variables, but are not exported.
Variables cannot be checked under Heads if they do not have explicit exports under board configuration.
Instead of exporting those from all current and next platforms, the current fix just checks the presence of fbwhiptail binary to set the background colors correctly.
Tested under:
- x230-hotp-maximized (fbwhiptail)
- x230-hotp-verification (newt, whiptail console without fb)
@MrChromebox please approve.
> Apply background colors when fbwhiptail binary is present

- patches/coreboot-4.15/0001-soc-skylake-me.c-Print-status-regardless-of-device-e.patch
- patches/coreboot-4.15/0002-soc-cannonlake-me.c-Print-status-regardless-of-devic.patch
- patches/coreboot-4.15/0003-soc-intel-cannonlake-Add-PcieRpHotPlug-config-to-FSP.patch
- patches/coreboot-4.15/0004-soc-intel-skylake-move-heci_init-from-bootblock-to-r.patch
- patches/coreboot-4.15/0005-soc-intel-common-cse-Drop-CSE-library-usage-in-bootb.patch
- patches/coreboot-4.15/0006-soc-intel-common-cse-skip-heci_init-if-HECI1-is-disa.patch
- patches/coreboot-4.15/0007-mb-purism-librem_skl-disable-HECI-PCI-device.patch
Add patches to coreboot 4.15 to:
- show ME status even when device is disabled
- fix PCIe RP hotplug on Librem 14
- fix ME reset timeout on Librem 13/15
This synchronizes with Purism's coreboot 4.15-Purism-3 tag.
> patches/coreboot-4.15: Add Librem 4.15 patches

- boards/kgpe-d16_server-whiptail/kgpe-d16_server-whiptail.config
- boards/kgpe-d16_server/kgpe-d16_server.config
- boards/kgpe-d16_workstation-usb_keyboard/kgpe-d16_workstation-usb_keyboard.config
- boards/kgpe-d16_workstation/kgpe-d16_workstation.config
- boards/t420-hotp-maximized/t420-hotp-maximized.config
- boards/t430-flash/t430-flash.config
- boards/t430-hotp-verification/t430-hotp-verification.config
- boards/t520-hotp-maximized/t520-hotp-maximized.config
- boards/x220-hotp-maximized/x220-hotp-maximized.config
- boards/x230-flash/x230-flash.config
- boards/x230-hotp-verification/x230-hotp-verification.config
fixes #1096 where some boards had wrong CONFIG_BOARD_NAME or it was missing.
> boards/* : Add/uniformize missing CONFIG_BOARD_NAME for coreboot boards

- modules/coreboot
`:?` is invalid. `?=` defines if not previously defined (was not passed to 4.11 nor 4.13 coreboot builds)
> modules/coreboot: pass EXTRA_FLAGS correctly to non coreboot 4.15 coreboot builds

- .circleci/config.yml
- Makefile
- blobs/xx30/vbios_t530.sh
- blobs/xx30/vbios_w530.sh
- patches/coreboot-4.11/0073-build-race-condition-fixes.patch
~This is WIP.~
In an attempt to investigate why car.data is not build under coreboot 4.11 builds under debian-11, I've decided to check what is going on in Heads' build system, which at the end of the day is supposed to do the right thing until we have something better to use.
To have reproducible builds, we are supposed to have fixed versions of some tools, prior of building anything in the hope of producing reproducible output:
- known make version being same as defined in module definition
- known gawk version being same as defined in module definition
- musl-cross-make toolchain as defined per musl-cross module definition to build all modules **_but coreboot_**
- coreboot version specific build toolchain so coreboot parts are reproducible.
- At that point, we should have reproducible …
> make coreboot 4.11 platforms buildable under recent OSea (CircleCI builds on debian-11 here)

- initrd/bin/gui-init
It is going to be enabled later anyway (if CONFIG_HOTPKEY=y), so it can
also be simplified by enabling it at the very beginning.
This enables USB keyboard consistently during all boot menus, including
the "No Bootable OS Found" prompt. It isn't a big deal for "normal"
laptop usage, but it is important for automatic tests and also
non-laptop systems.
> Move enable_usb earlier

- initrd/bin/gui-init
- initrd/bin/oem-factory-reset
oem-factory-reset: adapt code so that custom passphrases can be provided by user without changing oem factory reset workflow.
oem-factory-reset: output provisioned secrets on screen at the end of of the process for users to review prior of reboot.
fixes: https://github.com/osresearch/heads/issues/1067 (while not reusing https://source.puri.sm/firmware/pureboot/-/commit/c912f256fde7bcd0039e23170260f629521fb819#a6c94f7187de316661024d0ce4f8837609a83516_89_91)
> oem-factory-reset: reownership with custom PINs/passpwords prompt without changing OEM workflow

- initrd/bin/gui-init
- initrd/bin/network-init-recovery
- initrd/bin/oem-factory-reset
- initrd/bin/reencrypt-luks
OEM Factory Reset/Re-Ownership: Addition of LUKS reencryption + passphrase change options
- initrd/bin/reencrypt-luks: add functions for reencryption and passphrase change. Feeds itself from external provisioning or local provisioning
- Also exports passphrases so that oem-factory-reset can use them prior of cleaning (unsetting variables and wiping secrets)
- Also adds function to test provided Disk Recovery Key passphrase, added in previous reencryption and passphrase change functions, looping there forever if wrong.
- initrd/bin/oem-factory-reset: add 2 additional prompts defaulting to N, also explaining why its important.
- initrd/bin/oem-factory-reset: adds a measured integrity output prior of prompts. Goal is for stating TOTP/HOTP/boot detached signed measurements prior of initiating …
> OEM Factory Reset/Re-Ownership: Addition of LUKS reencryption + passphrase change options

- blobs/xx30/vbios_t530.sh
- blobs/xx30/vbios_w530.sh
- Better error handling (exits earlier)
- Better scoping of UEFIExtract to only deal with FL1 files, which is where vbios files are to be extracted from. 
- Adds sudo calls where required (CircleCI runs at root. Local builds failed, as reported https://github.com/osresearch/heads/issues/1110#issuecomment-1038223970
@eganonoa @MrChromebox : improvements welcome. CircleCI works and extraction is confirmed to build locally as well over debian-11. Consequently, this is considered a bug in original code and should be merged ASAP.
Fixes #1085
> Improvements on xx30 vbios scripts

- .circleci/config.yml
Heads buildstystem:
- Makefile logic will download modules packages under ./packages, check itheir integrity, then extract it and patch extraction directory ONLY if no corresponding .*_verify files are found under ./packages directory. They are extracted under build/modulename-ver/ where patches are applied prior of building them.
- build/module* .configured is written when packages are configured under build/modulename-ver/.configured
- build/modules* .build is written when packages are built under build/modulename-ver/.build
CircleCI caching subsystem notes:
- A cache name tag is calculated in the prep_env stage early at each beginning of a workflow, and consists of a cache name, appended by a calculated digest signature (which is the final hash of hashed files (the hash of a digest).
- …
> CircleCI cache: have all cache layers caching packages directory.

- initrd/bin/kexec-select-boot
* kexec-select-boot: Simplify boot menu entries
* kexec-select-boot: Simplify boot selection confirmation, reverse order
* kexec-select-boot: Skip duplicate prompt when setting new default boot entry
* kexec-select-boot: use 'fold' to wrap kernel args at 80 char
igned-off-by: Matt DeVillier <matt.devillier@puri.sm>
> Kexec QOL Improvements

- initrd/bin/kexec-select-boot
Was introduced at commit ba054b15c3740228ba3e327c3442a9f7594a9fe8 (fold wrapper to show boot options selected)
> Bugfix: fix accidental removal of --menu statement in kexec-select-boot 

- initrd/bin/oem-factory-reset
This continues to generate checksums and detach sign them per cached GPG User PIN in all OEM Factory Reset/Re-Ownership use cases, but does not set a default boot option when kexec_encrypted_disks.txt is present on /boot (flag left on /boot when a TPM Disk Unlock Key was previously setuped.)
The user hitting Default Boot post Re-Ownership will go through the setup of a new boot default, which will ask him to setup a Disk Unlock Key if desired. Without this, hitting Default Boot goes into asking the user for its Disk Recovery Key passphrase and confuses the user, requiring him to manually setup a default boot option (Boot Options-> Show OS boot Options) to setup a TPM Disk Unlock Key.
Tested: OEM Factory Reset. Manual setup of a default boot option with LUKS Disk Unlock Key (Otherwise …
> oem-factory-reset: Only set default boot option if no TPM Disk Unlock Key

- initrd/bin/network-init-recovery
- initrd/etc/functions
This is a local fix where eth0 gets full randomized mac address if board config is a maximized board config when calling network-init script.
network-init script doesn't do anything fancy for the moment, but permits to set RTC clock from NTP source.
So in the present case, it makes sure that if multiple maximized machines are to be connected on LAN, each of them will get a IP from DHCP requests and then be able to sync NTP with the network.
@MrChromebox please review.
> Add Heads mac address randomization for maximized boards

- initrd/bin/oem-factory-reset
- initrd/etc/luks-functions
Since /etc/luks-functions are currently exporting passphrases tested good per `cryptsetup test` to be reused in caller code,
the logic calling both luks_reencrypt and luks_change_passphrase, testing for non-empty luks_current_Disk_Recovery_Key_passphrase was bogus (always exported).
This commit includes a new  `luks_new_Disk_Recovery_Key_desired` variable which is set when reencryption is desired.
The 3 use cases (reencrypt+passphrase change, reencrypt no passphrase change and passphrase change alone) now only test
for `luks_new_Disk_Recovery_Key_desired` and `luks_new_Disk_Recovery_Key_passphrase_desired` and nothing else, for clarity as well.
luks-functions: make warning consistent + typo correction.
@MrChromebox please review.
> bugfix: oem-factory-reset - permit LUKS passphrase change without reencryption

- modules/mbedtls
- licensing change to APACHE 2.0
- sha256sum changed too
Fixes #1173 
TODO: bump version to 3.1+, not trivial.
> modules/mbetls: move dl from tls.mbed.org to github

- .circleci/config.yml
Coreboot 4.11 boards are not properly building as of now.
coreboot.pre fails to depend on .car.data because of a race condition that can only be mitigated by single threading CPUS=
This is unrelated to other changes.
KGPE-D16 will soon enough depend on dasharo coreboot and be ported upstream later on.
Fixes #1180
> CircleCI: Remove coreboot 4.11 builds

- initrd/bin/gui-init
Fixes #1181 
@MrChromebox Please review.
Question: should we also add commit ID?
> gui-init: Have TPMTOTP QrCode named under TOTP app with $BOARD_NAME

- .circleci/config.yml
Global Makefile is the most effective modifier of builds.
As soon as the global Makefile changes, so should not be reused caches having measured a different Makefile.
Short reminder of how CircleCI caches work:
- keys are built on top of text. Best is hashes.
- The most automated way to do this is to create a digest and measure it to create unique key in for m of a sha256sum
- That key is generated on top of git downloaded tree components on each CircleCI prep_env step
- If a cache is available matching the same key being a string $cache_type-$hash-$CACHE_VERSION, then that cache is retrieved and extracted on top of downloaded git tree and CircleCI proceeds with its step.
---
We have 3 caches "types":
- Biggest (all): includes all built components and downloaded packages
- all modules and …
> .circleci/config.yml: Add Makefile as part of measured files for cache downloads

- initrd/bin/gui-init
- initrd/init
A small piece of https://github.com/osresearch/heads/pull/836 ([this file](https://github.com/osresearch/heads/pull/836/files#diff-63d474ce25ab525343c0d061b286b1cd45199cd14fdf9ea535f396fd8be5de45)) to avoid adding `-tmp`/`-no-tpm` board variants in https://github.com/osresearch/heads/pull/1002 and other cases.
Is it OK that after `gui-init` prints `Unable to locate /boot files on any mounted disk` message `$skip_to_menu` equals `true`, `$TOTP` isn't set and main menu doesn't display `NO TPM` until you press <kbd>r</kbd>?
Also, with these changes all `CONFIG_TPM` in board files is ignored, so maybe it needs to be removed from them or dynamic behaviour should be used only if `CONFIG_TPM=y` in config.
> init: assign CONFIG_TPM depending on /dev/tpm0 presence

- Makefile
- patches/flashrom-b1f858f65b2abd276542650d8cb9e382da258967/0100-enable-kgpe-d16.patch
- patches/gpg2-2.2.21.patch
Otherwise binary patches cannot be patched/created
Additional fixes needed
- flashrom patch was invalid and got catched by git apply. Correcting
- gpg2-2.2.21.patch was pointing to bad target. Correcting
----
This commit is included by #967 as of now, otherwise coreboot patchsets (and other patches including binary patches) cannot be applied by patch.
Once this is merged, #967 will be rebased on master.
Without the present change, [x230-fhd-edp patchset, targeting graphical configuration blob (vbt) cannot be applied](https://github.com/osresearch/heads/pull/967/files#diff-4eeb4abb7c19d1c1aaf5c84906b32586eb85230907d6ee12e2bc885178a23dfbR132-R172)
Discussions on removing `--reject`, adding `--3way` etc happened under https://github.com/osresearch/heads/pull/967#issuecomment-1217046809 …
> Makefile: replace patch with git apply

- Makefile
Revert Makefile to use patch -p1 instead of git apply, something changed and this doesn't apply the same.
Fixed regression for first built boards: https://app.circleci.com/pipelines/github/tlaurion/heads/1166/workflows/76e79591-dbaa-4900-9756-f9c6cc86f793
Path of patch application are not good for the moment for `patches/module-version/*.patch`, that is when multiple patches are to be applied on decompressed archive dir.
https://app.circleci.com/pipelines/github/osresearch/heads/437/workflows/00934a21-4834-4398-b41a-b5488135d3eb/jobs/4311?invite=true#step-103-55
Will work on this separately without affecting master for the time being.
Sorry for the noise and revert of that change.
> Emergency revert of git apply instead of patch

- .github/ISSUE_TEMPLATE/bug-report-for-everything-except-build-errors.md
- .github/ISSUE_TEMPLATE/bug-report-for-heads-build-errors.md
- .github/ISSUE_TEMPLATE/feature_request.md
This is a cleaned-up PR with issue templates (see #1069).  The reasoning behind #1069 was as follows:
In its current form, Heads has so many variables it appears very difficult to determine the cause of issues being raised. There is a risk in development being stalled or taken off track by a rise of very specific bugs reported that are not readily reproducible or only appears in a very specific set of circumstances. In addition, its increasingly difficult to identify separate feature requests from bug reports.
These three templates provide templates for: (a) feature requests; (b) bug reports related to build errors for Heads; and (c) bug reports that come from the flashing or operation of Heads. They are designed to better help the identification of the best people to respond to any given …
> Use issue templates

- Makefile
Force length of commit id to 7 characters to that variation of length is not a source of reproducibility errors.
Fixes #1227
> fixate HEADS_GIT_VERSION to use a commit id of 7 characters

- initrd/bin/flash.sh
- Have Talos II supported by detecting correctly size of mtd chip (not internal: different flashrom output needs to be parsed for chip size)
- Read SPI content only once: 66% speedup (TOCTOU? Don't think so, nothing should happen in parallel when flashing in single user mode)
- Have the main flash_progress loop not break, but break in flash_rom state subcases (otherwise, verifying step was breaking)
Next steps: 
- Review changes tested under https://github.com/osresearch/heads/commit/76d7ee5f1993594b5e1cf5e05708c3c8bb864859 for later work (after upstream flashrom project fixes its `flashrom --progress` reporting under https://ticket.coreboot.org/issues/390)
- Have https://github.com/osresearch/heads/blob/master/patches/flashrom-b1f858f65b2abd276542650d8cb9e382da258967/0100-enable-kgpe-d16. …
> flash.sh: UX and logic fixes

- initrd/bin/mount-usb
- initrd/etc/functions
Extract exclusion for unpartitioned block device of partitioned media to gui_functions, and exclude them even if kernel hasn't listed the partitions yet.  (Fixes flash/USB boot prompts incorrectly trying to use the whole device for partitioned media the first time.)
Ignore block devices of size 0, like empty USB SD card readers.
Signed-off-by: Jonathon Hall <jonathon.hall@puri.sm>
> mount-usb: Improve reliability with partitioned disks

- Makefile
Change patch to git apply, permitting to apply binary diffs and give better hints on console of builds when patches fail to be applied.
Was already tested fonctional against:
- talos II #1002 (https://app.circleci.com/pipelines/github/tlaurion/heads/1170/workflows/d05b2802-ddb3-45e5-84d1-9fdc1d0cd395)
- master (https://app.circleci.com/pipelines/github/tlaurion/heads/1170/workflows/d05b2802-ddb3-45e5-84d1-9fdc1d0cd395/jobs/9805)
@SergiiDmytruk ?
> Change patch to git apply

- initrd/bin/kexec-parse-boot
Fixes #1239, #1001
Ignore device specs in GRUB boot entry paths, assume they point to /boot.  Check that boot kernel and initrd are valid files; ignore options that would not be able to boot.
Tested booting the following ISOs (directly written to USB disk): Debian (live KDE, netinst still has graphics init issues), Fedora KDE, Qubes, PureOS.
Tested booting Qubes ISO from ext4-formatted USB disk (loopback ISO boot).
Tested booting installed PureOS and Qubes.
> Ignore grub device specs in boot entry paths

- boards/qemu-coreboot-fbwhiptail-tpm1-hotp/qemu-coreboot-fbwhiptail-tpm1-hotp.config
- boards/qemu-coreboot-whiptail-tpm1/qemu-coreboot-whiptail-tpm1.config
As a result, you will get expected pause_recovery (etc/functions) output "Hit enter to proceed to recovery shell:" prompt on ttyS0 (stdio: where qemu is launched) while whiptail is shown only once on host (qemu/kvm). 
This is important in case of TPM, since entering recovery shell will invalidate measurements and prevent TPM disk encryption key to be unsealed if going to recovery shell.
By removing the CONFIG_BOOT_RECOVERY_SERIAL board configuration export, only dmesg is redirected to ttyS0 (helpful to debug)
> Add CONFIG_BOOT_RECOVERY_SERIAL to qemu board configs to interact with host through serial

- initrd/bin/config-gui.sh
- initrd/bin/flash-gui.sh
- initrd/bin/gpg-gui.sh
- initrd/bin/gui-init
- initrd/bin/kexec-select-boot
- initrd/bin/mount-usb
- initrd/bin/oem-factory-reset
- initrd/bin/usb-scan
- initrd/etc/gui_functions
So we have console logs to troubleshoot errors and catch them correctly
---
@JonathonHall-Purism linked to separate discussion.
This is useful to call scripts (eg. gui-init) from recovery shell so that scripts can be ctrl-c to see console output.
Any error should be corrected in caller scripts anyway and provide at least a warning (warn) to console.
> whiptail: no more whiptail reseting console on call (--clear)

- initrd/bin/gui-init
If the user selects "continue to main menu" from an error, do not show any more error prompts until reaching the main menu.
We still try to initialize everything (GPG, TOTP, HOTP) so that the main menu can still show TOTP/HOTP if GPG is not configured, etc., but no more prompts are shown after selecting "continue to main menu".
Signed-off-by: Jonathon Hall <jonathon.hall@puri.sm>
> gui-init: Always go to main menu when selecting "continue to main menu"

- patches/coreboot-4.11/0073-build-race-condition-fixes.patch
The last PR fixing these patches missed this one because it was mistakenly deleted and restored later.  Resulted in 'error: patch with only garbage at line 22'.
Built librem_l1um on Debian 11 host to verify.
Signed-off-by: Jonathon Hall <jonathon.hall@puri.sm>
> coreboot-4.11: Fix remaining patch to work with git apply

- boards/qemu-coreboot-whiptail-tpm1/qemu-coreboot-whiptail-tpm1.config
Trivial fix. Will merge directly: board is not fbwhiptail but whiptail, and not hotp but totp only.
> qemu-coreboot-whiptail-tpm1: correction of boardname to reflect reality

- Makefile
This patch changes the bash location in the makefile from /bin/bash to /usr/bin/env bash. The latter is a more reproducible location as it is common to more *nix systems which don't contain the former, such as NixOS.
> Makefile: Use path agnostic bash location

- initrd/bin/gui-init
Fixes https://github.com/osresearch/heads-wiki/issues/103 
@JonathonHall-Purism : comments?
Also note that we should maybe cover with one rock (two birds) https://github.com/osresearch/heads/issues/1266
> TOTP code mismatch: better guidelines in code

- initrd/etc/functions
This was exposed through testing #1262 and attempting to call `recovery` instead of `die` under proposed changeset under https://github.com/osresearch/heads/pull/1262#issuecomment-1381079323
This should be merged prior of #1262, which should be rebased on top of master.
> recovery call: since we operate under set -e, make sure that shred failing doesn't exit

- initrd/bin/gui-init
- initrd/etc/functions
Recently, fbwhiptail calls removed --clear as part of calls clearing console output in the goal of facilitating troubleshooting.
This PR:
- removes last two printf clear that were getting in the way of having traces on console output (functions)
- adds only needed printf clear on console, which is after output and scan of TPMTOTP QR code confirmed to be scanned by user (was a reboot under #1275)
Replaces #1275 
@JonathonHall-Purism : please review
> Adjust printf clears

- initrd/bin/kexec-save-default
fixes screwed commit 6f6f37ec3a8d7cab1c963ce4e6614f89132aeecf
@JonathonHall-Purism : otherwise scanning / not /boot
sorry about that.
> kexec-save-default: do /boot operation in subshell

- initrd/etc/functions
> /etc/functions: fix order when loading usb modules to prevent warning

- .gitattributes
Fix GitHub syntax highlighting for the Coreboot/Heads config files, and modules, which are all Makefiles.
See: https://github.com/github/linguist/blob/master/docs/overrides.md
> Add overrides for Makefile syntax highlighting

- modules/musl-cross
NixOS doesn't have a traditional FHS where echo is available at `/bin/echo`. Instead, we must rely on the PATH for any distribution-managed utilities. Reverses https://github.com/osresearch/heads/issues/106.
---
**Testing**
See: https://github.com/osresearch/heads/pull/1282/.
> modules/musl-cross: use echo from the PATH to support NixOS

- initrd/bin/gui-init
Fixes #1290 by calling warn if sealing-totp failed (nvram/ownership invalid) to tell user he should reset TPM first.
This happens on non-reset TPM only where sealing/unsealing fails, see #1290 for details.
----
Note that all `die` calls gui-init will die (exiting init). 
Any other script called by gui-init calling die function as expected.
@JonathonHall-Purism
> gui-init: warn the user when sealing measurements through TOTP/HOTP reset

- initrd/etc/functions
Adds check to detect device formatted as fat32 without partition table.
With fat32 fdisk does not print message about invalid partition table and instead it'll print an empty table with header. In both cases total output has the same length of 5 lines: 3 about device info, 1 empty line and the 5th will be the table header or invalid partition message.
So the amount of lines fdisk outputs is used to detect if it's a formatted device without partition table.
This fixes #1274 
Sample image of the empty table fdisk outputs.
Device format cases tested:
- Fat32 without partition table.
- Ext4 without partition table.
- MBR with single fat32 partition.
- GPT with single ext4 partition.
- USB drive with flashed live ISO
> /etc/functions: fix detection of virtual flash drive in qemu.

- initrd/bin/kexec-insert-key
- initrd/bin/kexec-save-default
This PR takes original work from @root-hardenedvault under #894 and supplements it to automatically parse selected default's boot's initrd file (compressed/uncompressed) to find OS defined crypttab entries.
It keeps track of OS deployed crypttab files and respects OS deployed options, overriding "none" to "/secret.key" and saves 
the overrides under `/boot/kexec_initrd_crypttab_overrides.txt` in the form of `crypttab_file/crypptab config lines` under `kexec-save-default`. 
`kexec-save-default` now informs the user of what was found and overridden, while `kexec-insert-key` applies ithose overrides, while also informing the user of twhat is to be applied through injected additioanl cpio through the final kexec call to the OS when adding a TPM disk unlock key at default boot selection.
If no …
> WiP : TPM disk unlock key setup (kexec-save-key) reuses OS initrd's crypttab files as base for /secret.key override (kexec-insert-key)

- initrd/bin/media-scan
- initrd/bin/usb-init
media-scan accepts direct input of existing blkid and mount that passed device to /media
> usb-scan->media-scan: usb-init calling media-scan usb

- .circleci/config.yml
More informative CircleCI output. 
Direct merge without consultation.
> CircleCI step name change : Make Board -> Make Board (FULL ORDERED BUILD LOGS HERE UNTIL JOB FAILED)

- README.md
Reverts last commit (README.md points to https://osresearch.net again)
> README: point to https://osresearch.net again (DNS name renewed)

- initrd/bin/oem-factory-reset
Fixes  #1076 and closes [heads-wiki#102](https://github.com/osresearch/heads-wiki/issues/102)
Code is from https://github.com/osresearch/heads-wiki/issues/102#issuecomment-1255464870 but instead of making a function and call, it's incorporated into the `gpg_key_reset` function after the Nitrokey AES key reset.
**To-Do:**
> Set forcesig if "not forced" after reset

- Makefile
pkg-config will still pick up system default directories from PKG_CONFIG_LIBDIR even if PKG_CONFIG_PATH is set.  Per the docs, cross compilation requires clearing PKG_CONFIG_PATH and setting PKG_CONFIG_LIBDIR (which is always searched after PKG_CONFIG_PATH).
Fixes issues observed in tpm2_retry branch picking up packages from host environment.
> Makefile: Fix cross compilation variables for pkg-config

- patches/util-linux-2.29.2.patch
patches/util-linux: patch configure script so that all hardcode_into_libs=yes -> hardcode_into_libs=no
Originally tested and documented under https://github.com/osresearch/heads/pull/1321#issuecomment-1452353251
Replaces #1321
> Fix util-linux reproducibility issue (libblkid.so.1)

- modules/coreboot
.xcompile was not found because it was quoted and shouldn't in coreboot module's makefile
Prior:
```
stat("\"/home/user/heads/build/x86/coreboot-4.13/.xcompile\"", 0x7ffe56e6cfd0) = -1 ENOENT (No such file or directory)
pipe([3, 4])                            = 0
fcntl(4, F_GETFD)                       = 0
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
fcntl(3, F_GETFD)                       = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=1024*1024}) = 0
prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=1024*1024}) = 0
stat("/usr/bin/env", {st_mode=S_IFREG|0755, st_size=48480, ...}) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000 …
```
> modules/coreboot: do not rebuild version specific coreboot's builstack at each board's make

- modules/cairo
- modules/cryptsetup
- modules/cryptsetup2
- modules/flashtools
- modules/gpg
- modules/gpg2
- modules/kexec
- modules/libassuan
- modules/libgcrypt
- modules/libgpg-error
- modules/libksba
- modules/libpng
- modules/libusb
- modules/libusb-compat
- modules/lvm2
- modules/mbedtls
- modules/newt
- modules/pinentry
- modules/pixman
- modules/qrencode
- modules/tpmtotp
- modules/util-linux
Adresses @aesrentai suggestion to pass modules optimization from O2 (performance) to Os (space) here: https://github.com/osresearch/heads/issues/590#issuecomment-821788703
Will comment on gains after build succeeds.
~Still impossible as of now to build xx30-flash boards on top of linux 5.10.4......~ EDIT: without kernel networking support, this now passes.
> Pass all modules from O2/O3 (optimized for speed) to Os (optimize for space)

- modules/flashtools
Changes to support ppc64 were merged upstream
> modules/flashtools : version bump back to osresearch/flashtools

- initrd/bin/kexec-save-default
- /tmp/initrd_extract was attempted to be deleted while under that directory when no crypttab found.
- changing of directory to / is non-conditional prior of deletion: move to cleaning step
- Clarity on message displayed to user when a generic crypttab will be generated in case of no OS override
Otherwise currently showing at setting TPM disk unlock key when setting default boot option on master:
> kexec-save-default: fix case when no crypttab found in initrd

- blobs/xx30/download_clean_me.sh
Without this, one always has to specify `-m` option, as [the CI does](https://github.com/osresearch/heads/blob/2995376cdaffae4457f3042bfdbd33414b475086/.circleci/config.yml#L98).
> download_clean_me.sh: Find me_cleaner in tree

- initrd/bin/oem-factory-reset
Problem
When using a custom password for TPM, the OEM re-ownership process is broken
Impact 
The OEM re-ownership process breaks for any user setting a custom password and not just using 12345678 
First appeared
https://github.com/osresearch/heads/commit/6923fb5e20cfb662b76c1d1fa48e245ecd8d79fb
Detail
on line 498, if blank, the TPM custom password is overwritten with TPM_PASS_DEF (eg, when no custom password is set by the user installing)
```
if [ "$TPM_PASS" == "" ]; then TPM_PASS=$TPM_PASS_DEF; fi
```
so far so good.  $TPM_PASS should be used for all TPM interaction from this point. $TMP_PASS_DEF is now a disposed of variable.
we see that happens when resetting the TPM on line 712 (generate_checksums) is that $TPM_PASS is used (correctly)
```## reset TPM and set password
if [ …
```
> fix broken OEM re-ownership process

- initrd/bin/oem-factory-reset
- Trace calls need to happen after sourcing /etc/functions not before
- Move sourcing of external files at beginning of file, remove /etc/functions sourcing duplicate
- gpg error redirection was sent to /dev/null where expected to be added to whiptail in case of error (2>&1 instead and redirection to file)
> oem-factory-reset: remove duplicates and add proper error redirection to file

- initrd/etc/ash_functions
- initrd/etc/functions
TPM2 board inclusion made bash required, and we missed early usb keyboard enablement+testing after moving some required init functions, but not all required ones, from functions to ash_functions, causing a regression on x230 usb-keyb and talos, requiring early usb keyboard support.
enable_usb function is moved /etc/ash_functions to be called from init, which otherwise don't find needed function, since init only sources the minimal ash_functions before switching to boot policy (gui-init or any other specified in board config)
That code is required to do measurements in PCR5 prior of actually loading the kernel modules drivers. 
/sbin/insmod is actually a wrapper script calling `busybox insmod` **after** having measured modules to be loaded.
This prevents unsealing secrets which requires …
> Fix usb keyboard at init

- boards/qemu-coreboot-fbwhiptail-tpm2-hotp/qemu-coreboot-fbwhiptail-tpm2-hotp.config
- boards/qemu-coreboot-fbwhiptail-tpm2/qemu-coreboot-fbwhiptail-tpm2.config
- boards/qemu-coreboot-whiptail-tpm2-hotp/qemu-coreboot-whiptail-tpm2-hotp.config
- boards/qemu-coreboot-whiptail-tpm2/qemu-coreboot-whiptail-tpm2.config
Since qemu boards are reference for TPM2 boards, it will remove a lot of future questions to have the PCAP debug related variable in board config under the debug section.
Changes it for the 4 current tpm2 boards in tree.
@JonathonHall-Purism : in link with questions already received https://matrix.to/#/!pAlHOfxQNPXOgFGTmo:matrix.org/$ZIbrfnsU668-yEzFoCyNGAOyg6mvtHwWAJkl26zukM0?via=matrix.org&via=nitro.chat&via=talk.puri.sm
> qemu-coreboot-*whiptail-tpm2-* boards: move TPM2 debug PCAP variable to debug section for clarity

- initrd/bin/kexec-select-boot
- initrd/bin/mount-usb
A few errors now show up under Bash that Ash had silently ignored.  It happens to behave correctly, but fix the errors.
> Fix benign script errors

- modules/coreboot
- modules/linux
Helper tools borrowed from #1351 
Will help me bumping 4.14 kernel configs straight to 5.10 with minimal changes and help other do so in the future.
The way I use them is the following:
`make BOARD=xyz linux.modify_and_save_oldconfig_in_place`: takes the in tree linux board config, modifies it through menuconfig (or not) and saves its oldconfig (full format) back in tree.
`make BOARD=xyz linux.modify_defconfig_in_place`:  takes the in tree linux board config, modifies it through menuconfig (or not) and saves its defconfig (variation from defaults for arch) back in tree.
Same applies with `make BOARD=xyz coreboot.modify_and_save_oldconfig_in_place` and `make BOARD=xyz coreboot.modify_defconfig_in_place`
---- 
@JonathonHall-Purism doesn't impact anything else then dev/maintenance cycle
> coreboot+linux modules: add helpers to edit config, save in oldconfig/defconfig

- modules/coreboot
Fixes https://github.com/osresearch/heads/issues/1370
Tested locally by doing two `make BOARD=t440-maximized`.  (coreboot 4.17 > 4.13)
Second build skips coreboot buildstack extraction, patching and building.
@JonathonHall-Purism please review (will check CircleCI output for different coreboot versions meanwhile. Second layer builds builds for same coreboot version should not build buildstack).
Addresses changeset https://review.coreboot.org/c/coreboot/+/28101
> coreboot: output xcompile into old shared location for all coreboot versions to prevent buildstack rebuild

- modules/bash
- patches/bash-5.1.16.patch
Removing debug info from bash.
Adding patch to disable bash auto increment of the build number that goes in the version string of the binary.
The increment is triggered when bash/configure is run and bash/.build file already exists.
Patch consists of removing the relevant flag from the call to helper script in makefile template.
Should fix bash reproducibility.
> Bash reproducibility

- initrd/bin/kexec-boot
- initrd/bin/kexec-iso-init
- initrd/bin/kexec-parse-boot
- initrd/bin/kexec-select-boot
- initrd/bin/media-scan
- initrd/bin/usb-init
- Add debug information from usb-init (or media-scan) up to kexec -e call
- Adds Tinycore iso magic (for Tinycore init to be able to find iso after successful kexec call)
- Adds the fix to isolinux parsing which was not dealing correctly with iso boot (where dd'ed iso was working)
Fixes #1347 
Fixes #1374 
@JonathonHall-Purism please review (this is different then #1351 which will be rebased on this when I have time to continue checking why we cannot have basic simple fb in absence of virtio fb under Tinycore's initrd)
@saper that should fix your issue under x230 with 4.x kernel which doen't suffer from 5.x-> Tinycore novga issue (like on qemu)
> Iso boot debugging and fixes

- patches/linux-4.14.62/0004-libsubcmd_Fix_use-after-free-for-realloc.patch
As discussed in #1392 , a use after free bug in the kernel prevents heads kernel being compiled on debian 12.
This has been fixed in #1393 for boards using 5.10.5
The bug also affects boards using kernel 4.14.62.  This PR will fix this and allow building of boards using this kernel on debian 12.
Clearly the future is for all boards to use 5.10 kernels (as per WIP #1381).  Nevertheless, might be sensible to fix in 4.14 branch in the interim until no boards use the old kernel.
> backport upstream patch for 4.14.62.  Allows building on debian 12

- modules/fbwhiptail
Updated to reproducible version of fbwhiptail.
Added flags to remove debug info.
Updated url to current one instead of going through redirect.
This fixes fbwhiptail reproducibility.
> modules/fbwhiptail: Update for reproducibility

- Makefile
Just a very minor fix for the `real.clean` and `modules.clean` Makefile targets - they haven't been adapted to the architecture hierarchy inside `build`.
> Makefile: adapt cleaning targets for arch directory

- Makefile
- modules/linux
This adds an easy way to compare sizes of packed stripped built binaries and libs in cpios, compressed under initrd and the kernel bzImage and coreboot rom, both on screen and into sizes.txt.
This is basically a copy paste + `stat -c "%8s:%n"` under Makefile & modules/linux, reusing HASHES code but duplicating for SIZES.
Note that the sizes.txt can be sorted for human eyes through a simple `cat sizes.txt | sort -h`.
I would love to have this merged now so that master can be compared to branches that are rebased upon it.
---
@JonathonHall-Purism : can you review+approve asap please?
> Makefile: have sizes report output on screen and into sizes.txt

- .circleci/config.yml
CircleCI keeps steps output forever as opposed to artifacts.
This permits us to keep sizes.txt output as a step for a board forever, just like for hashes.
@JonathonHall-Purism
> CircleCI: have sizes output kept in CircleCI forever just as hashes

- initrd/bin/flash.sh
- modules/flashrom
Based on commit https://github.com/JonathonHall-Purism/heads/commit/2bb58f7f25bd55564132f48eaaa8ceb942f2b6ee
- Extended to not have the progress bar stuck at 99%. Progress bar drawing under Heads still needed until properly implemented upstream see https://ticket.coreboot.org/issues/390
- Removes flashrom DUMMY and AST1100 on both x86 and ppc64.
- AST1100 can be added through board config option instead of bloating smaller SPI boards ROMs.
TODO: probably split flashrom into flashrom-stable/flashrom-upstream/flashrom-dasharo and have boards use the one needed. I suspect flashrom-stable will be even smaller.
---
Good news is that #1422  #1381 and this PR merged under #1398 can be compiled for legacy boards, dodging #1421 issue for the moment.
> flashrom: bump flashrom to upstream 1.3 and fix flash.sh progress_bar

- boards/qemu-coreboot-fbwhiptail-tpm1-hotp/qemu-coreboot-fbwhiptail-tpm1-hotp.md
A few lines in the documentation got truncated somehow.  Restored the swtpm instructions from some notes and rewrote the others.
> qemu-coreboot-fbwhiptail-tpm1-hotp: Fix truncated documentation lines

- initrd/bin/kexec-boot
- initrd/bin/kexec-insert-key
- patches/kexec-2.0.26.patch
So that actual boards and future boards show that they might stay in the dark until OS loads the proper DRM/FB drivers if unsupported by kexec
Linux kernel changed since 4.19.
Since then, buffer addresses are generally hidden and cannot be directly passed to another kernel through kexec anymore.
Workarounds have been applied to linux kernel and kexec patch for i915drmfb, while others are currently unsupported out of the box.
Transition out of this is to have all boards rely on linux kernel's simplefb frambebuffer.
Meanwhile, other boards relying on kexec will show an error like the following that is shown for qemu boards as of today:
The `kexec -l` call outputs an error about virtio_gpudrmfb driver, which cannot expose its fb address to kexec and therefore, the user stays in the dark …
> Kexec cosmetic fixes

- patches/coreboot-4.17/0004-acpi-unix2-mirror.patch
- patches/coreboot-talos_2/0002-acpi-unix2-mirror.patch
I built Librem 14 locally to verify the coreboot-4.17 patch.  Copied verbatim to coreboot-talos_2, will check CI build status.
> Use Intel mirror for acpi-unix2 20220331

- patches/coreboot-4.11/0070-crossgcc-iasl-2021-instead-of-2018_fix-old_coreboot-build-on-newer-platforms.patch
Download from distfiles.macports.org instead, same hash.
kgpe-d16 and librem-l1um depend on coreboot 4.11 still today in tree, even though building is successful only on debian-10 and those boards are not built on CircleCI anymore (debian-11). 
Fixing so people building 4.11 today are still successful on debian-10.
4.19+ already depends on github.com releases tarballs. 
REF for upstream issue: https://review.coreboot.org/c/coreboot/+/76399
@JonathonHall-Purism please make sure it works, local build taking forever here.
Note: note that none the past coreboot versions in tree outside of 4.19+ will build. from now on.
Ranting begins here: maybe reproducible builds is just a piped dream in current software supply chain ecosystem. Ranting ends here.
> coreboot 4.11 needs acpica which moved from acpica.org to intel. 

- boards/qemu-coreboot-fbwhiptail-tpm1-hotp/qemu-coreboot-fbwhiptail-tpm1-hotp.config
- boards/qemu-coreboot-fbwhiptail-tpm1/qemu-coreboot-fbwhiptail-tpm1.config
- boards/qemu-coreboot-fbwhiptail-tpm2-hotp/qemu-coreboot-fbwhiptail-tpm2-hotp.config
- boards/qemu-coreboot-fbwhiptail-tpm2/qemu-coreboot-fbwhiptail-tpm2.config
- boards/qemu-coreboot-whiptail-tpm1-hotp/qemu-coreboot-whiptail-tpm1-hotp.config
- boards/qemu-coreboot-whiptail-tpm1/qemu-coreboot-whiptail-tpm1.config
- boards/qemu-coreboot-whiptail-tpm2-hotp/qemu-coreboot-whiptail-tpm2-hotp.config
- boards/qemu-coreboot-whiptail-tpm2/qemu-coreboot-whiptail-tpm2.config
Was CONFIG_BASIC_BOOT instead of CONFIG_BASIC expected.
@3hhh I would recommend playing with this in the goal of #1441.
@JonathonHall-Purism simple review please.
Also some tweaks seem needed to enable autoboot on basic basic boot: current basic boot enablement thinks autoboot is configured because not negated?
> Qemu boards: typo correction in comment to manually enable Basic Boot mode

- modules/ioport
Annoying.
@JonathonHall-Purism will try to reach you to have this approved but otherwise will push without review, works locally and stops builds from succeeding in other PRs [otherwise](https://app.circleci.com/pipelines/github/tlaurion/heads/1901/workflows/ad521f6c-e272-4b13-8b8c-358b9e07f4da/jobs/29234?invite=true#step-103-26502_94):
```
2023-08-10 21:03:53-04:00 WGET https://people.redhat.com/rjones/ioport/files/ioport-1.2.tar.gz
if ! wget -O "/root/project/packages/x86/ioport-1.2.tar.gz.tmp" https://people.redhat.com/rjones/ioport/files/ioport-1.2.tar.gz ; then exit 1 ; fi ; mv "/root/project/packages/x86/ioport-1.2.tar.gz.tmp" "/root/project/packages/x86/ioport-1.2.tar.gz" 
--2023-08-10 21:03:53--  https://people.redhat.com/rjones/ioport/files/ioport-1.2.tar.gz
Resolving …
```
> ioport: changing url to debian, same hash. First need to go into #1198 direction

- modules/ioport
Sorry for the noise.
Went to fast: https://github.com/osresearch/heads/commit/a276b05a445dc9cec03cd2e88d3e82e30e6a8556 was an http url, not https.
This is why reviewing is important :/
Supersedes #1463, pushing now.
> ioport: changing url to debian https server, same hash. First need to go into #1198 direction

- boards/qemu-coreboot-fbwhiptail-tpm1-hotp/qemu-coreboot-fbwhiptail-tpm1-hotp.config
- boards/qemu-coreboot-fbwhiptail-tpm1/qemu-coreboot-fbwhiptail-tpm1.config
- boards/qemu-coreboot-fbwhiptail-tpm2-hotp/qemu-coreboot-fbwhiptail-tpm2-hotp.config
- boards/qemu-coreboot-fbwhiptail-tpm2/qemu-coreboot-fbwhiptail-tpm2.config
- boards/qemu-coreboot-whiptail-tpm1-hotp/qemu-coreboot-whiptail-tpm1-hotp.config
- boards/qemu-coreboot-whiptail-tpm1/qemu-coreboot-whiptail-tpm1.config
- boards/qemu-coreboot-whiptail-tpm2-hotp/qemu-coreboot-whiptail-tpm2-hotp.config
- boards/qemu-coreboot-whiptail-tpm2/qemu-coreboot-whiptail-tpm2.config
- initrd/bin/oem-factory-reset
- modules/hotp-verification
- Bumping version of  [hotp-verification to 1.4](https://github.com/Nitrokey/nitrokey-hotp-verification/releases/tag/v1.4) 
- Add support under oem-factory-reset to provision subkeys with p256
- move enable-usb earlier in oem-factory-reset
- Add USB Security dongle detction by USB ID
- If NK3, use p256 algo in oem-factory-reset
---
Originally first introduced in: #1417
> Nitrokey 3 support

- initrd/bin/flash-gui.sh
Return is not valid outside of a function - exit instead.
> initrd/bin/flash-gui.sh: Exit instead of errant return

- initrd/bin/unseal-hotp
If the secret can't be unsealed, die immediately rather than continuing on to generate errors.
> initrd/bin/unseal-hotp: Prevent script errors if unseal fails

- boards/librem_mini/initrd/bin/set_ec_poweron.sh
- boards/librem_mini_v2/initrd/bin/set_ec_poweron.sh
- config/coreboot-librem_mini.config
- config/coreboot-librem_mini_v2.config
- modules/coreboot
This is 4.21-Purism-1 plus a fix for native graphics init on Mini v1/v2: HDMI1 is enabled so passive DisplayPort to DVI/HDMI adapters will work.
> modules/coreboot: Update Purism coreboot to 24e2f7e4

- .circleci/config.yml
Fixes #1507 by explicitly stating under CircleCI config (list of debian-11 packages explicitly needed to build Heads) that libncurses5-dev is needed so that qubes-os debian-11-minimal, debian-11 install and docker can be used with same apt packages installed to build openssl module, required for boards depending on tpm2 toolstack.
> CircleCI: fix debian-11 packages dependencies (#1507)

- initrd/etc/ash_functions
Fixes #1516
Otherwise TPM2 output for pcrs call under ash_fonctions pollutes kmsg and console output and prevents resealing of Disk Unlock Key with passphrase.
With this fix
> BugFix: Pass debug call output to kmsg one line at a time

- initrd/bin/flash-gui.sh
Add ROM and ROM hash when non-npf file is selected for flashing as per  https://github.com/osresearch/heads/pull/1514#issuecomment-1787258746
----
Old
- Refactoring of arguments parsing, so they are not positional.
- Internal usage of -i argument from flash-gui.sh to flash.sh to bypass hash validation prompt in case of npf
- Rewording of flash-gui.sh output in case of non-npf file
- Adds this validation prompt so the user can validate hash output from external source prior of accepting flashing
Notes:
- Talos II still only user of tgz archive which is similar to npf and doesn't show prompt either.
> bin/flash-gui.sh & initrd/bin/flash.sh: Show SHA256SUM for manual verification prior of flashing

- .circleci/config.yml
- Makefile
- boards/UNTESTED_t430-legacy-flash/UNTESTED_t430-legacy-flash.config
- boards/talos-2/talos-2.config
- boards/x230-legacy-flash/x230-legacy-flash.config
- create-npf.sh
- initrd/bin/flash-gui.sh
- initrd/bin/flash.sh
The NPF file extension can be configured on a per-board basis, default is ZIP.  Fixed some issues in the implementation (don't require /tmp/verified_rom/ in sha256sum.txt, show integrity error instead of dying if ZIP itself is corrupt as that is more likely, etc.), details in commit messages.
Update package is built in default target now, removed create_npf.sh.
@daringer This should still be compatible with any npf archives already published (/tmp/verified_rom/ prefix is removed if present).  Do you want `export CONFIG_BRAND_UPDATE_PKG_EXT=npf` added to your boards?
@tlaurion I refactored prompts a little so .tgz only appears for talos-2 (and .rom does not appear on talos-2).  I can't really do any further refactoring to better integrate talos-2 with the zip method.  If you want to …
> flash-gui.sh: Extend NPF archive format to ZIP, improve workflow

- initrd/bin/oem-factory-reset
The call to `hotp_verification regenerate` seems to leave the communication in a bad state, thus the following `gpg` calls fail. With this workaround `scdaemon` will resart with the next `gpg` call.
> oem-factory-reset: kill scdaemon after aes regenerate on nk storage

- initrd/bin/oem-factory-reset
This partially fixes #1537, but while the increased width wouldn't be a problem on the NV41 AFAICT, I don't know about other machines.
I don't know what @tlaurion means with "busybox's folding", which may be a better solution.
> Use a wider window to show the secrets

- initrd/bin/oem-factory-reset
- initrd/etc/luks-functions
Fixes point 3. from #1539 and other minor points in discussion there. Summary of changes:
1. If user selects both reencrypt and change passphrase during OEM factory reset, then the passphrase will be changed first so as not to leave a copy of the new volume key encrypted with potentially compromised defaults (e.g. "PleaseChangeMe" passphrase from OEM) lying around on disk if disk is COW media such as SSD and does not garbage collect properly. This fixes point 3. from #1539.
2. Added check for exported new passphrase to reencrypt function, so that it uses the new one if it was set.
3. Removed all instances of incorrect term "Recovery Disk Key" and replaced with "Disk Recovery Key".
4. Changed the warning message of reencrypt function to better reflect the process and warn user not to …
> Luks functions text patch & change order of reencrypt and passphrase change

- initrd/bin/tpmr
- change TPM DUK sealing which needs to be on cached TPM owner passphrase
- Add debugging that was needed to spot the issue
Fixes #1565
> tpmr: fix TPM Disk Unlock Key which was not using proper cached TPM owner passphrase.

- modules/pixman
Haven't found same archive elsewhere with same hash. 
Adds up to https://github.com/linuxboot/heads/issues/1198
> modules/pixman: www.cairographics.org down again. Use web.archive.org archive.

- modules/cairo
Haven't found same archive elsewhere with same hash.
Adds up to https://github.com/linuxboot/heads/issues/1198
> modules/cairo: www.cairographics.org down again. Use web.archive.org archive

- Makefile
- bin/fetch_coreboot_crossgcc_archive.sh
- bin/fetch_source_archive.sh
- modules/coreboot
- patches/coreboot-4.11/0070-crossgcc-iasl-2021-instead-of-2018_fix-old_coreboot-build-on-newer-platforms.patch
Try to download dependency source packages from mirrors if the primary source fails or the archive has changed.
Move the download and verify logic to bin/fetch_source_archive.sh.  The mirror list is here, currently only
https://storage.puri.sm/heads-packages/, but others can be added.  The mirror list is randomized to load each mirror equally.
The verify logic is moved to this script too so it can fail over to a mirror (or another mirror) if a mismatched archive is served, not just for a failure.  Makefile no longer needs to verify separately and there are no separate .*-_verify files any more, the archive is only moved to its final place once verified.
Add `packages` target to just fetch all needed packages for a board, facilitates seeding a mirror.
Closes #1198
> Makefile: Support mirrors for dependency source packages

- initrd/bin/seal-hotpkey
If we can't mount /boot, show a meaningful error rather than dropping to a recovery shell.
Dropping to a recovery shell should be a last resort.  Users that know how to use the recovery shell know how to get there.  Users that don't know how to use it can be completely stuck and may not know how to get back to the menu or even how to turn off the device.
This happened to a user after reinstalling the OS.  PureBoot offered to re-seal TOTP/HOTP, but attempting to do so just went to recovery because the old /boot partition no longer existed, there wasn't any clear path to get the system back in working order.
The easiest way to test this is to just remove the SSD, then attempt to boot and seal TOTP/HOTP.
> initrd/bin/seal-hotpkey: Show error if /boot can't be mounted

- initrd/.gnupg/gpg.conf
- modules/gpg2
Otherwise under debian-12 qemu/talos II (not sure why not on other platforms?!):
```
~ # gpg --detach-sign /tmp/debug.log 
gpg: error running '//bin/dirmngr': probably not installed
gpg: failed to start dirmngr '//bin/dirmngr': Configuration error
gpg: can't connect to the dirmngr: Configuration error
gpg: no default secret key: No dirmngr
gpg: signing failed: No dirmngr
```
Alternative: pack dirmngr, but as of now, doesn't make sense since we implicitely state we do not want dirmngr but that isn't respected. When/if we need key download and have on-demand networking for more advanced/dynamic Heads config: revisit.
> gpg2: make sure dirmngr is not spawn to refresh keys under initrd/.gnupg/gpg.conf

- boards/UNTESTED_p8z77-m_pro-tpm1-hotp-maximized/UNTESTED_p8z77-m_pro-tpm1-hotp-maximized.config
- boards/UNTESTED_t430-hotp-legacy/UNTESTED_t430-hotp-legacy.config
- boards/UNTESTED_t520-hotp-maximized/UNTESTED_t520-hotp-maximized.config
- boards/UNTESTED_t530-dgpu-hotp-maximized/UNTESTED_t530-dgpu-hotp-maximized.config
- boards/UNTESTED_t530-hotp-maximized/UNTESTED_t530-hotp-maximized.config
- boards/UNTESTED_w530-dgpu-K1000m-hotp-maximized/UNTESTED_w530-dgpu-K1000m-hotp-maximized.config
- boards/UNTESTED_w530-dgpu-K2000m-hotp-maximized/UNTESTED_w530-dgpu-K2000m-hotp-maximized.config
- boards/qemu-coreboot-fbwhiptail-tpm1-hotp/qemu-coreboot-fbwhiptail-tpm1-hotp.config
- boards/qemu-coreboot-fbwhiptail-tpm2-hotp/qemu-coreboot-fbwhiptail-tpm2-hotp.config
- boards/qemu-coreboot-whiptail-tpm1-hotp/qemu-coreboot-whiptail-tpm1-hotp.config
- boards/qemu-coreboot-whiptail-tpm2-hotp/qemu-coreboot-whiptail-tpm2-hotp.config
- boards/t420-hotp-maximized/t420-hotp-maximized.config
- boards/t430-hotp-maximized/t430-hotp-maximized.config
- boards/t440p-hotp-maximized/t440p-hotp-maximized.config
- boards/w530-hotp-maximized/w530-hotp-maximized.config
- boards/w541-hotp-maximized/w541-hotp-maximized.config
- boards/x220-hotp-maximized/x220-hotp-maximized.config
- boards/x230-hotp-legacy/x230-hotp-legacy.config
- boards/x230-hotp-maximized-fhd_edp/x230-hotp-maximized-fhd_edp.config
- boards/x230-hotp-maximized/x230-hotp-maximized.config
- boards/x230-hotp-maximized_usb-kb/x230-hotp-maximized_usb-kb.config
- boards/z220-cmt-hotp-maximized/z220-cmt-hotp-maximized.config
- initrd/bin/config-gui.sh
Automatic boot can be configured in the configuration GUI.  Options are disable, 1 second, 5 seconds, or 10 seconds.
Users asked me for this :grin: 
Closes #1441 (where @3hhh request for 3s is not in yet, but PR welcome)
> initrd/bin/config-gui.sh: Allow configuring automatic boot

- initrd/bin/flash-gui.sh
Show messages for media errors in flash-gui.sh, either when enumerating ROMs or reading a plain ROM.  (Reading a ZIP package is already OK, the unzip fails and it falls through to the integrity check error.)
A user had I/O errors when enumerating ROMs, which just returns to the main menu with no explanation.  (find errors will be on the recovery console.)  Show an error in that case suggesting to check the disk, reformat, or try a different disk.
I believe the user's case was due to filesystem corruption, but I can reproduce the same find errors with the following:
* With an ancient/slow flash drive, produce a lot of dummy files so the 'find' will take long enough to yank the disk
* `for i in $(seq 1 50000); do dd if=/dev/urandom bs=1K count=1 of=<disk>/$(printf rom%05i.rom $i) …
> Show error messages for various media errors in flash-gui.sh

- bin/fetch_coreboot_crossgcc_archive.sh
Changes in things like modules/coreboot will check the coreboot toolchain archives again.  We reuse the cached archive already, but the final ln -s may fail if the link already exists.  Remove it first and link again.
> bin/fetch_coreboot_crossgcc_archive.sh: ln -s again if link exists

- modules/gpg2
- modules/libusb-compat
- modules/popt
popt: too old to have a working config.guess (2009. version bump) 
libusb-compat: not needed for gpg2. Adapt into module (reverse dep hack not needed in module anymore) 
gpg2: depend on libusb not libusb-compat
> ppc64le builder required changes

- initrd/bin/inject_firmware.sh
The function is 'warn', not 'WARN'.
> initrd/bin/inject_firmware.sh: Fix warning command

- FAQ.md
- initrd/bin/kexec-insert-key
- initrd/bin/kexec-save-default
- initrd/bin/kexec-save-key
- initrd/bin/kexec-seal-key
- initrd/bin/kexec-unseal-key
- initrd/bin/oem-factory-reset
- initrd/etc/functions
- initrd/etc/luks-functions
- modules/zstd
#1588 related: fixes retry. Left behind: capslock key detection and fix.
@JonathonHall-Purism please review
Tested:
- lukskillslot of slot 1 when two available.
- lukschangepassword without specifying slot so that slot 0 LUKS Disk Recovery Key is put under slot1 where no slot 0 exist.
-  on TPM DUK addition, warning showed to user to repair manual config which is unsupported
- when manually fixed as suggested, both slot 1 and slot 0 exist and Heads detects and warns correctly on both LUSKv1 and LUKSv2
- TPM DUK loops for 1/3 to 3/3 and warns that capslock might be the cause of failing.
- After 3 bad attempts, normal codepath continue proposing user to type LUKS Disk Recovery Key password in OS.
Basically, the loop code was bogues because of pipefail, TPM DUK passphrase failing to unseal …
> Fix TPM DUK retry loop (bogus), uniformize related vocabulary

- patches/coreboot-nitrokey-clevo_release/0002-dasharo-hardcode-me.patch
fixes Nitrokey/heads#39
Dasharo v1.7.2 introduced a feature to always set the ME state during boot based on the EDK2 defined values. 
This led to the ME being activated in Nitrokey's v2.4 release, this PR fixes this by hard-coding the EDK2 defined values.
This PR is intentionally minimal to minimize testing and release fast - the Nitropad releases, will be build from this [branch](https://github.com/Nitrokey/heads/tree/nitropad-release-v2.4.1). 
We are currently testing - it affects anyways the `coreboot-nitrokey` module exclusively - so don't see further needs for testing - we will not only test our branch, but also the upstream artifacts. Once the tests are done I will promote this PR to "ready-for-review".
> coreboot-nitrokey: hard-code ME state during boot

- modules/openssl
Passing the path to libgcc in LDFLAGS appears to no longer be needed. Removing this fixes compilation on a freshly cloned repo.
Fixes #1507
> modules/openssl: remove libgcc path hack

- initrd/bin/root-hashes-gui.sh
- initrd/etc/functions
- initrd/init
Since exFAT support was enabled, spurious exFAT errors appear in the console in some cases:
* mounting iso9660 hybrid USB
* searching for /boot when a bios-grub, LVM, or LUKS partition precedes boot
In both cases, avoid trying to mount things as exFAT that aren't exFAT.  exfat is moved below iso9660 in automatic mount detection by creating /etc/filesystems (using /proc/filesystems).  Detecting /boot skips some things it knows are not mountable as /boot (bios-grub, LUKS, LVM PV), and also avoids trying the same device twice.  Details in commits.
Tested with mount-usb:
* mount iso9660 hybrid image on USB, verify no more exFAT errors
* mount exFAT partition
* format exFAT over iso9660 hybrid image with mkfs.exfat in Heads (without partition table), mount, verify new exFAT is found correctly …
> init: Silence exFAT errors when mounting iso9660; reorder exfat last

- initrd/etc/ash_functions
Otherwise we get ehci-pci and xhci_hcd kernel messages in dmesg debug AFTER "Verifying presence of GPG card" which explains why dongle might not be found in time and fails in oem-factory-reset
Fixes https://github.com/Nitrokey/heads/issues/48
@JonathonHall-Purism @daringer
> BUGFIX: ash_functions: move sleep 2 after all usb modules being loaded

- boards/qemu-coreboot-fbwhiptail-tpm1-hotp/qemu-coreboot-fbwhiptail-tpm1-hotp.config
- boards/qemu-coreboot-fbwhiptail-tpm1/qemu-coreboot-fbwhiptail-tpm1.config
- boards/qemu-coreboot-fbwhiptail-tpm2-hotp/qemu-coreboot-fbwhiptail-tpm2-hotp.config
- boards/qemu-coreboot-fbwhiptail-tpm2/qemu-coreboot-fbwhiptail-tpm2.config
- boards/qemu-coreboot-whiptail-tpm1-hotp/qemu-coreboot-whiptail-tpm1-hotp.config
- boards/qemu-coreboot-whiptail-tpm1/qemu-coreboot-whiptail-tpm1.config
- boards/qemu-coreboot-whiptail-tpm2-hotp/qemu-coreboot-whiptail-tpm2-hotp.config
- boards/qemu-coreboot-whiptail-tpm2/qemu-coreboot-whiptail-tpm2.config
- initrd/bin/kexec-boot
- initrd/bin/kexec-insert-key
- initrd/bin/oem-factory-reset
- initrd/bin/seal-hotpkey
- initrd/etc/ash_functions
- initrd/etc/functions
- initrd/init
Goal here was to have `kexec -l` output to kmesg so also to console when BOARD is in DEBUG+TRACE mode (configuration settings menu + flash)
@JonathonHall-Purism  please review
A variation of this commit is under #1640 to troubleshoot #1641 more easily and permit users to provide /tmp/debug.log
> Improve DEBUG and DO_WITH_DEBUG output handling to also keep output of DO_WITH_DEBUG commands

- initrd/bin/oem-factory-reset
Addresses part of #1645:
Lowers the User GPG PIN minimum length to 6 to be consistent with NitroKey app / docs and default PIN length (Admin GPG PIN minimum length is still 8).
> Address inconsistency between docs and OEM factory reset User GPG PIN minimum length requirement

- FAQ.md
- Makefile
- initrd/bin/kexec-insert-key
- initrd/bin/kexec-save-default
- initrd/bin/kexec-select-boot
- initrd/bin/kexec-unseal-key
- initrd/bin/oem-factory-reset
- initrd/init
Fixes #1092 
Supersedes #1093 
- Rework of https://github.com/linuxboot/heads/commit/ed1c23aaa3f8d5264c5b6e5f66ad359406bed166 (credit to @root-hardenedvault) thank you!)
- Addresses and correct self-review under https://github.com/linuxboot/heads/pull/1093 (@root-hardenedvault : you don't answer often here!)
- ~kexec-unseal-key: Warn a user who attempts to default boot while his Disk Unlock Key passphrase fails to unseal because LUKS headers changed (https://github.com/linuxboot/heads/pull/1093 (comment))~ EDIT: everything move to kexec-insert-key to check header checksum part of detached signed hash digest, before attempting TPM DUK unseal op. 
- kexec-seal-key: Identical as in https://github.com/linuxboot/heads/commit/ed1c23aaa3f8d5264c5b6e5f66ad359406bed166
- ~kexec-add-key: Tell the …
> LUKS header change validation upon sealing and unsealing ops

- .circleci/config.yml
- flake.nix
- targets/qemu.mk
- flake.nix: add canokey-qemu lib, derivate qemu on tope of it and have qemu_kvm depend on qemu derivative
- targets/qemu.mk: modified to had canokey support by default if no "USB_TOKEN=" specified on make run call
- CircleCI: base docker image pull on v0.1.6 containing the newly added derivatives
----
Fixes #1670
Closes https://github.com/linuxboot/heads/issues/1207
---
Finally, bye errors of qemu TCG on top of qemu on top of qubesos with usb error -32.
It's alive!!!
----
Someone.... wants to implement reverse HOTP inside of canokey-qemu???
> flake.nix + qemu.mk : add working qemu-canokey usable from all qemu boards by default

- .circleci/config.yml
- README.md
- flake.lock
- flake.nix
~WiP: not yet under nixos-unstable. See https://github.com/linuxboot/heads/pull/1687/commits/c7d1495a0a1478c872ad62e3cd9c9d14d96043ff log for details.~ 
EDIT: part of nixos-unstable as of this PR, having called `nix flake update` to update flake.lock to pin to new package list including qemu built with canokey by default as per https://nixpk.gs/pr-tracker.html?pr=311914 PR inclusion and hydra having built all derivatives, downloadable from cache for flake.nix based develop to build docker image reproducibly.
Notes:
- the magical part of this is that the nix develop produced docker image is reproducible. One can recreate the docker image per instructions and then pull my image and see that all layers were already cached! This is pure magic.
- Compressed Docker image size went from 1.43Gb …
> Use nixos-unstable channel's prebuilt qemu_full with canokey support builtin from nix cache

- README.md
README.md updated in build instructions and in particular an error encountered because of kernel.yama.ptrace_scope during docker image build
> Updated README.md for kernel.yama.ptrace_scope issues

- .circleci/config.yml
Librem L1UM (v1) works in CI, re-enable it in CircleCI.
I put it in front of the KGPE-D16 boards just because I don't think a maintained board should depend on unmaintained boards, but I can tweak it if there's a reason to have them in a different order.
> circleci: Add Librem L1UM to CI, in front of unmaintained 4.11 boards

- Makefile
- initrd/bin/config-gui.sh
- initrd/bin/flash-gui.sh
- initrd/bin/gpg-gui.sh
- initrd/bin/gui-init
- initrd/bin/gui-init-basic
- initrd/bin/kexec-select-boot
- initrd/bin/media-scan
- initrd/bin/mount-usb
- initrd/bin/oem-factory-reset
- initrd/bin/oem-system-info-xx30
- initrd/bin/root-hashes-gui.sh
- initrd/bin/seal-hotpkey
- initrd/etc/gui_functions
- initrd/etc/luks-functions
- initrd/init
- modules/ncurses
- Tested on text mode MSI dGPU board.
- Tested on Chromebook GOP framebuffer mode.
I think I got all of the occurrences in which colors are modified. Open to modification of variable names etc.
> Add support for modifying background color when using Newt. Adds ncurses to provide terminfo file.

- README.md
More aesthetic then anything else. Will help figure out problems later on if any.
@JonathonHall-Purism was used to make sure everything was kosher and reproducible starting fresh from README.md instructions to rebuild identical v0.1.9 and push it to latest under  https://github.com/linuxboot/heads/pull/1713#issuecomment-2217969429 as can be seen under https://hub.docker.com/r/tlaurion/heads-dev-env/tags with same hashes as before.
Please merge.
> README.md: Make docker image build more verbose on console, unify

- unmaintained_boards/README.md
Discussion about this here:
https://github.com/linuxboot/heads/issues/1682
--- 
This takes @fhvyhjriur's #1696 commit and sign it with my signature.
This supersedes #1696 and closes #1682.
> Update README.md : cherry-pick of PR #1696's commit with me signing.

- .circleci/config.yml
- Makefile
- flake.nix
- Includes #1732 (supersedes it)
- Add  moreutils into nix docker image (v0.2.1) to have each make step timestamps
- Add per arch (x86/ppc64) intermediary CircleCI step to build musl-cross-make per arch
---
Closes #1731
All other branches will need to be rebased on master, CircleCI seems to throttle bandwidth since a change around 2024 July 16
@JonathonHall-Purism please review/approve.
TODO upon merge:
> Fix master's CircleCI builds (Bandwidth throttling making all boards depending on coreboot forks to exceed 1h step's max build time) 

- CONTRIBUTING.md
- README.md
Any comments welcome! This sets guidelines for contributions to heads and heads-wiki repos. 
Thanks for your collaboration into drafting this with me!
> Guidelines for contributing under CONTRIBUTING.md

- targets/qemu.mk
Commit 46cad549 ("WiP flake.nix: make docker image usable for...") added 'root' to the swtpm_setup call, but broke skip-if-exist because the flags are supposed to be comma-separated.  swtpm_setup was ignoring skip-if-exist and would fail if the config files exist.
Put a comma there so it works again.
> targets/qemu.mk: Fix skip-if-exist in swtpm_setup

- initrd/bin/flash.sh
Flashrom dropped --progress output under 1.2.
flashrom 1.4 still has no --progress output.
---
Heads implemented in-house progress output as a workaround until fixed upstream.
That never happened.
This is still opened issue https://ticket.coreboot.org/issues/390
---
As per https://github.com/linuxboot/heads/pull/1753#discussion_r1725694439 @JonathonHall-Purism comment:
> What would you think about removing the progress bar? The dream would be to rework it (maybe doing it in flashrom itself, or at least providing a reliably-parseable progress output), but the current implementation is a huge pain, I don't feel it adds enough value to outweigh the pain. For comparison the read step takes a comparable amount of time and does not have a progress bar.
---
So here, we drop progress output and …
> flash.sh: drop inhouse progress output on console when flashing with flashrom

- initrd/bin/flash.sh
Add a warning prior of calling flashrom reminding end user to not poweroff and wait while flashing operation finishes.
Message prior of version dependent flashrom output will now be :
> WARNING: Do not power off computer. Updating firmware, this will take a few minutes...
---
Reasoning, as per https://github.com/linuxboot/heads/pull/1753#issuecomment-2307255469:
> So on master with flashrom 1.3:
> - tested (DEBUG ON) https://output.circle-artifacts.com/output/job/78a45204-7736-4f87-bf5d-922b48469782/artifacts/0/build/x86/x230-hotp-maximized/heads-x230-hotp-maximized-v0.2.0-2282-g1e03e8c.zip
> - Scary, but ok:
> ![signal-2024-08-23-102929](https://github.com/user-attachments/assets/5f726b8f-cfb0-4dbe-8e47-bba32cdef831)
> 
> 
> Under this PR containing flashrom 1.4:
> - tested (DEBUG ON) …
> flash.sh: Add warning to remind user to not interfere with flashrom operations that will follow

- bin/seed_package_mirror.sh
Run this to download all the needed package artifacts for a mirror.
> bin/seed_package_mirror.sh: Script to seed a package mirror

- initrd/init
As of today, somone deciding to Config -> Enable DEBUG + flash cannot simply go back to Config-> Disable DEBUG + flash and have its system permit unsealing previous TPMTOTP + TPM DUK and go on.
This fixes config.user being injected over and over the same TPM related settings by making sure they are not preent prior of reinjectig them.
> init: make sure config.user is overriden only with new values so that going DEBUG/undoing can work reproducibly

- initrd/bin/gui-init
- initrd/bin/oem-factory-reset
fix bugs introduced by #1698:
- whiptail_error was self calling itself in case no usb security dongle was connected instead of asking the user to plug it in and try again
- whiptail_error and whiptail_warning are overrides of sourced /etc/gui_functions
- therefore, whiptail_error calling whiptail_error was self calling passing wrong paramters and whiptail prompt was never showed.
- fixed by renaming oem-factory-reset's whiptail_error into local_whiptail_error function and changing whiptail_error_die and the only place where this fonction was called directly
--- 
Superseeds #1777 
Addresses https://github.com/linuxboot/heads/issues/1395#issuecomment-2308014938 : thanks for reporting @arhabd
---
No need for review after testing, "emergency" bugfix
> oem-factory-reset gui-init: fix whiptail_error segfaulting because selfcalling itself; fix typo in gui-init

- initrd/etc/gui_functions
Aesthetic fix. Otherwise interrupting default boot and next action write on same line.
@JonathonHall-Purism quick review. Approve & Merge when done!
> gui_functions: add newline after message telling user that automatic boot will happen unless interrupted

- boards/qemu-coreboot-whiptail-tpm2/qemu-coreboot-whiptail-tpm2.config
bugfix, was not supposed to be in non-debug in master.
> qemu-coreboot-whiptail-tpm2 board: reenable DEBUG + TRACING

- initrd/etc/ash_functions
> etc/ash_functions: remove TRACE_FUNC that cannot be used in ash, only under bash

- bin/fetch_source_archive.sh
storage.puri.st is an alternate host name for storage.puri.sm, in case there is another issue with the .sm name registration.
> bin/fetch_source_archive.sh: Add storage.puri.st mirror

- initrd/bin/config-gui.sh
Early Recovery Shell access (`r` pressed around seeing asciiart): /boot is not mounted, so need to call helper first before attempting to do operations on /boot.
Also, code was using pipe (`|`) instead of or pipe (`||`) to make sure pipefail would not happen on previous error commands.
Flagged because ./gnupg contains directories which failed to be deleted throwing error on recovery console, breaking script.
> config-gui.sh: fix bug happening when clearing all user config settings/calling config-gui.sh from recovery shell

- patches/coreboot-24.02.01/0004-cbmem_tpm-clear_whole_log_on_creation.patch
- patches/coreboot-dasharo-unreleased/0004-cbmem_tpm-clear_whole_log_on_creation.patch
- patches/coreboot-purism/0001-cbmem_tpm-clear_whole_log_on_creation.patch
fix #1608 for Dasharo, 24.02.01 and Purism coreboot forks
@JonathonHall-Purism please review
> patches/coreboot-*: fix tpm1 cbmem crash on 'cbmem -L'

- Makefile
- targets/split_8mb4mb.mk
fix https://github.com/linuxboot/heads/issues/1534
> BUGFIX: targets/split_8mb4mb.mk Makefile: Make sure top/bottom/rom hash+size are always outputted in console+hashes.txt+sizes.txt

- boards/qemu-coreboot-fbwhiptail-tpm1-hotp-prod/qemu-coreboot-fbwhiptail-tpm1-hotp-prod.config
- boards/qemu-coreboot-fbwhiptail-tpm1-prod/qemu-coreboot-fbwhiptail-tpm1-prod.config
- boards/qemu-coreboot-fbwhiptail-tpm2-hotp-prod/qemu-coreboot-fbwhiptail-tpm2-hotp-prod.config
- boards/qemu-coreboot-fbwhiptail-tpm2-prod/qemu-coreboot-fbwhiptail-tpm2-prod.config
- boards/qemu-coreboot-whiptail-tpm1-hotp-prod/qemu-coreboot-whiptail-tpm1-hotp-prod.config
- boards/qemu-coreboot-whiptail-tpm1-prod/qemu-coreboot-whiptail-tpm1-prod.config
- boards/qemu-coreboot-whiptail-tpm2-hotp-prod/qemu-coreboot-whiptail-tpm2-hotp-prod.config
- boards/qemu-coreboot-whiptail-tpm2-prod/qemu-coreboot-whiptail-tpm2-prod.config
Those basically turn off TRACING, DEBUGGING and PCAP output as opposed to their standard non `-prod` counterpart:
```
#Enable DEBUG output
#export CONFIG_DEBUG_OUTPUT=y
#export CONFIG_ENABLE_FUNCTION_TRACING_OUTPUT=y
#Enable TPM2 pcap output under /tmp
#export CONFIG_TPM2_CAPTURE_PCAP=y
```
This is to facilitate non-platform specific features in virtualized environment.
Note that :
- coreboot config still enables high verbosity kernel output, but once Heads is running, the output is similar to production for tpm1/tpm2/hotp/non-hotp variants.
- OEM only ship HOTP variants
- HOTP variants still not play well with qemu tcg mode (non-kvm/non-nested virt environements like QubesOS: can't fix).
---
Will be used to develop #1822
> boards/qemu*: add "prod" variants, not built by CircleCI as of now, to test Heads prod console output

- docker_latest.sh
- docker_local_dev.sh
- docker_repro.sh
This pull request includes changes to improve the handling of Docker images and the management of USB devices in the `docker_latest.sh`, `docker_local_dev.sh`, and `docker_repro.sh` scripts. The most important changes include setting Docker image variables, enhancing the `kill_usb_processes` function, and modifying the Docker run commands to handle USB device access more intelligently.
* Added a `DOCKER_IMAGE` variable to store the Docker image name in `docker_latest.sh` and `docker_local_dev.sh`. This improves consistency and makes it easier to update the image name in the future. [[1]](diffhunk://#diff-d7f6f52a5aca03eec4bb0d5bd60bf208ee67f1e951257dbfae0c663c517d76c5R5) [[2]](diffhunk://#diff-fc7abd574dec7a1330541376511d8bddd07d46e30d4242f437db2bfdb062a60cR3-R5)
* Enhanced the …
> docker_* helpers: pass usb host controllers to docker only if usb devices are connected, unify, bugfixes

- modules/lvm2
This fixes #1857
Was artifact of lvm2 version bump that happened under #1541.
TODO: figure out what still bled here to cause discrepancy, will attach diffoscope logs to #1857
> modules/lvm2: define /run relative paths (not sure why circleci remote docker default run dir != local run dir)

- initrd/bin/unpack_initramfs.sh
Closes https://github.com/linuxboot/heads/issues/1644 : was preventing to setup TPM DUK key because initrd couldn't be unpacked and repacked on the fly to be passed at kexec call to contain unsealed DUK key for final OS to pick up and use to unlock LUKS on boot.
- reformat with tabs and unify
[95c6eb5](https://github.com/linuxboot/heads/pull/1860/commits/95c6eb5c498bebc028cd92d62c83e33c2be3ed2e):
- adds xz unpacking that was missing and needed for debian derivatives.
- other format added in comments so easy to test when testing candidates will be reported in the wild
Ubuntu 24.10 switched from lz4 to zstd which was already supported, so does not add lz4 but still closes #1644 :)
---
**xz unpacking**
Before:
After this PR:
Which permitted to extract exfat.ko size, which was needed for …
> initrd/bin/unpack_initramfs.sh: add xz unpacking support.

- modules/flashprog
- We use https://github.com/SourceArcade/flashprog/commit/eb2c04185f8f471c768b742d66e4c552effdd9cb (2024-11-21 1.3+ bugfixes) 
-  meteor lake support is https://github.com/SourceArcade/flashprog/commit/5e0d9b04a07f5646038020e1a45dd04c0b14e8f3 is from 1.3 (3 weeks ago)
To be tested under #1846 and reported functional so I can press merge button. Will test on nv41 and x230 on my side, seeing changes, we should not have regressions
CC @i-c-o-n @mkopec 
----
Test regression (once Ci builds everything supported today) on my side for 
Other:
> modules/flashprog: bump to latest commit, including support for meteor lake

- modules/coreboot
Here are the changes (mostly irrelevant to Heads) that were merged after https://github.com/linuxboot/heads/pull/1846:
- Support for capsule updates (inactive for Heads build)
- Added NovaCustom MTL dGPU variants
- EC firmware update in coreboot (inactive for Heads build)
Changes that affect V560TU:
- Added support for reading power adapter wattage via ACPI
- Fixes for USB not working
- Add AC/DC loadline programming, for better stability
- Fixes for ME disable
- Fixes for Ethernet detection
I've tested booting into Qubes, ethernet detection, and USB type-A.
tlaurion edit: took https://github.com/linuxboot/heads/pull/1889#issuecomment-2598297536 content
> modules/coreboot: set Dasharo coreboot fork rev to the main dasharo branch

- initrd/bin/oem-factory-reset
nk3 was not tested on non-hotp boards. Make sure both htop_verification and nk3 is present before resetting Secrets App
> non-hotp boards: skip Secrets App reset with hotp_verification if binary doesn't exit

- blobs/xx30/optiplex_7010_9010.sh
Also fix path where file is found in zip.
Emergency bugfix since master doesn't build. Merging.
Will try to find archive somewhere else.
Fixes https://github.com/linuxboot/heads/issues/1915
> blobs/xx30/optiplex_7010_9010.sh: use web.arhive.org to download zip containing ivy/sandy file now missing upstream.

- bin/seed_package_mirror.sh
Board name was changed due to being untested.  It still builds, so the packages still sync to mirrors for now.
> bin/seed_package_mirror.sh: Update talos-2 -> UNTESTED_talos-2

- .circleci/config.yml
Fixes https://github.com/linuxboot/heads/issues/1937
(will wait for build to finish and merge without review. Marking as bug)
> bugfix: readd x230-hotp-maximized board build in CircleCI (was dropped because replaced by t480-hotp-maximized by error)

- .circleci/config.yml
- blobs/xx80/download_clean_deguard_me_pad_tb.sh
- modules/coreboot
Fixes: #1946 #1948 
https://review.coreboot.org is having HTTPS issue. Reported on coreboot matrix channel, but need to build.
Log from CircleCI failing when trying to pull deguard: https://app.circleci.com/pipelines/github/tlaurion/heads/3267/workflows/588f8aeb-4d73-4f71-9e6e-fd286e46353e/jobs/66442/parallel-runs/0/steps/0-111
Reasoning:
We might dislike GitHub, but when comes maintaining a project and using free systems for bandwidth and CI because reproducibility and prosperity needed in time/cost efficiency, we need to rely on systems that don't randomly fall. 
Using GitHub mirrors fulfills that purpose here.
> bugfix: modules/coreboot + blobs/xx80: rely on github for git, not review.coreboot.org

- .circleci/config.yml
Fixes https://github.com/linuxboot/heads/issues/1948 (hopefully for real this time)
---
First layer cache of CircleCI is reused when more complete cache reusal are invalidated: that is, to not compiled musl-cross-make from source for x86/ppc64 at each build when any other thing changed under Heads.
Unfortunately, https://github.com/linuxboot/heads/pull/1947 was incomplete in that regard, as showed per build:
- last save cache step https://app.circleci.com/pipelines/github/tlaurion/heads/3270/workflows/07dee00e-926e-4023-b8a7-669078e6ef31/jobs/66483
- first layer cache saving https://app.circleci.com/pipelines/github/tlaurion/heads/3270/workflows/07dee00e-926e-4023-b8a7-669078e6ef31/jobs/66483
- Warning: could not archive /root/heads/build/ppc64/musl-cross-make-38e52db8358c043ae82b346a2e6e6 …
> CircleCI: first layer cache: musl-cross-make+packages downloaded, was still pointing to old musl-cross-make

- initrd/bin/kexec-save-default
- initrd/etc/luks-functions
Fixes #1957 
under saving default boot option (not appearing anymore)
under oem-factory-reset, when saying N to defaults and Y to either changing LUKS passphrase/ reencrypting (not appearing anymore):
----
TODO: eventually refactor this out or silence no encrypted lvm found echos in code: who use encrypted LVM nowadays? I think this was pre QubesOS 3.2 era but not even sure anymore.
> UX bugfix: kexec-save-default: suppress "Failed to set up async io, using sync io" warning thrown by lvm vgscan

- patches/coreboot-24.12/0010-cbmem_tpm-clear_whole_log_on_creation.patch
Fixes https://github.com/linuxboot/heads/issues/1956
This is is still unmerged coreboot upstream since 24.02.01 (meaning more than a year now: February 2024) : https://review.coreboot.org/c/coreboot/+/84926
Cleaner solution would be to clear whole area on creation: https://review.coreboot.org/c/coreboot/+/84927, but this patch doesn't apply cleanly and is not even under review yet. 
@marmarek let me know if that fixes it for you. I cannot reproduce on my side aymore.
> patches/coreboot-24.12/0010-cbmem_tpm-clear_whole_log_on_creation.patch: readd missing uptream cbmem patch for TPM 1.2

- bin/find_undocumented_config.sh
- doc/config.md
- doc/logging.md
- initrd/etc/functions
Start documenting some design aspects of Heads to aid future PR discussions.
Logging has changed quite a few times, and it tends to be difficult to review because we don't have established expectations for how logging behaves.  Logging guidelines are helpful when adding features to keep logging consistent.
We have a lot more config variables now than in the past.  Only some of them are intended to be configured by the user in config.user, and it's not always clear which those are.
The logging documentation is fairly complete if we all agree on it :slightly_smiling_face:   Comments welcome, let's establish a common expectation.
The config documentation is not complete, there are many more variables not documented.  Help appreciated :slightly_smiling_face:  If we agree on the structure, we …
> doc: Start documenting Heads logging and configuration variables

- .circleci/config.yml
- flake.nix
- modules/musl-cross-make
Fix bug for cache reuse introduce when switching from x230 -> t480 for first board being build (but not switching x230->t480 for musl-cross-make at the same time under https://github.com/linuxboot/heads/pull/1908)
Test made from this PR:
- Reusal of stage 1 cache only (musl-cross-make cache)  workflow https://app.circleci.com/pipelines/github/tlaurion/heads/3314/workflows/e588480d-d13a-49e0-a1b6-78fed839b70b
- See prep_env step restoring first and smallest cache layer " nix-docker-heads-coreboot-musl-cross-make" at https://app.circleci.com/pipelines/github/tlaurion/heads/3314/workflows/e588480d-d13a-49e0-a1b6-78fed839b70b/jobs/67599/parallel-runs/0/steps/0-107
- We changed modules/musl-cross-make at pipeline https://app.circleci.com/pipelines/github/tlaurion/heads/3315/workflows/9bc8a009-6 …
> Fix CicleCI cache usage; add docker proc tools for debugging (flake.nix + docker 0.2.5 upload)

- Makefile
Improves collaboration with Makefile real.remove_canary_files-extract_patch_rebuild_what_changed helper:
- if canary is not found but coreboot fork directory exists: do not attempt to git clone; git reset instead and reuse previous logic (try to apply patches since .patched got wipe, if fails, revert patches and reapply, and build clean while reusing past built artifacts to reduced build time). Typically builds everything from source while reusing reusable built objects within 5 minutes on my machine.
- if canary is not found and coreboot dir doesn't exist: git clone and build clean (meaning also rebuilding buildstack, version reusable build artifacts and boards artifacts clean, which is what takes 45 minutes per board, clean, on CircleCI).
Fix issues when building multiple boards not …
> Makefile: make sure coreboot forks do the right thing when there is no .canary file but coreboot fork directory exists

- Makefile
fixes #1969
- fix regression where board.cpio was built inconditionally. Revert to pre-#1961 logic
- cleanup of data.cpio cconstruction, which still gives same cpio hash on my side and same content, will know if works with repro from issue
@JonathonHall-Purism Can you review this doesn't introduce something stupid like #1961 did?
----
Test:
Once again, building any board which include kbd keymaps, produces on my side with this PR:
- librem_11
```
911ff63584bd4f3115efe4fe44aacec29dca47bc0e32f1d7d546ddacf266eb02  /home/user/heads/build/x86/librem_11/data.cpio
2505216:/home/user/heads/build/x86/librem_11/data.cpio
```
- t480-hotp-maximized
```
2025-05-14 19:51:51+00:00 INSTALL-DATA build/x86/kbd-2.6.1/data/keymaps => usr/lib/kbd/keymaps
2025-05-14 19:51:51+00:00 INSTALL-DATA …
```
> bugfix: Fix data.cpio reproductibility issue introduced by #1961 

- Makefile
- modules/busybox
Fixes #1969 in https://github.com/linuxboot/heads/commit/f9afeb71dda233aaafcd87a128e21660f455344a
data.cpio should have hash of 879be3583e8a7ad429e969cba378d000f36cfd7d11acbebda78c0f0bb94eab1f for most boards. 
Verified over Circleci t480, x230. And local builds. 
----
TLDR: kbd archive contained hardlinked files which cp -a --remove-destination was not able to reproducibly put in data temp dir.
---
Details : 
There was an issue where initrd_tmp_dir was used to create tools.cpio and wipe that dir, while data.cpio was subdirectory of initrd_tmp_dir. This PR seperates tools.cpio temp dir from data.cpio temp dir:
- tools.cpio:	initrd_tmp_dir/tools/{bin,lib}
- data.cpio:	initrd_tmp_dir/data
So that when wiping happens of a subdir, this doesn't affect others:
- initrd_tmp_dir = mktemp -d
- …
> Makefile: initrd refactoring and data.cpio simplification

- boards/qemu-coreboot-fbwhiptail-tpm1-prod/qemu-coreboot-fbwhiptail-tpm1-prod.config
- boards/qemu-coreboot-fbwhiptail-tpm1/qemu-coreboot-fbwhiptail-tpm1.config
`qemu-coreboot-fbwhiptail-tpm1` and `qemu-coreboot-fbwhiptail-tpm1-prod` use `coreboot-qemu-tpm2.config` and `coreboot-qemu-tpm2-prod.config` respectively.
This PR makes them use the qemu tmp1 coreboot config.
> `qemu-coreboot-fbwhiptail-tpm1(-prod).config` coreboot config mismatch
