linuxboot/heads

modules/flashrom

This adds skylake support in flashrom.

Update flashrom to 1.0

---

initrd/bin/flashrom-x230.sh
modules/pciutils
patches/flashrom-1.0/0100-enable-kgpe-d16.patch
patches/flashrom-1.0/0101-enable-thinkpad-x220.patch

Also fix up flashrom-x230.sh command only read bios area

Add back flashrom support for KGPE-D16

---

initrd/bin/kexec-boot

Keep Xen cmdline arguments while appending Heads required ones. 

---

initrd/bin/x230-flash.init

flashrom-x230.sh is now flash.sh

initrd: x230-flash: fix commandline instructions for flashing

---

initrd/bin/flash-gui.sh
initrd/bin/gui-init
initrd/bin/kexec-select-boot
initrd/bin/unseal-hotp
initrd/bin/usb-scan
initrd/init

a handful of small, unrelated fixes/improvements. If individual PRs for each are preferred, then no problem submitting as such

Small fixes

---

Makefile
boards/qemu-coreboot/qemu-coreboot.config
modules/msrtools

`rdmsr`, `wrmsr` and `cpuid` for debugging and research.

add Intel msrtools commands

---

initrd/bin/oem-factory-reset

As is in many cases in Heads, not any key will work, just Enter.

oem-factory-reset: Fix description for rebooting when finished

---

modules/musl-cross
patches/musl-cross-1952975.patch

this should fix issues with compressed ELF header sections.

update musl-cross to 1952975

---

boards/kgpe-d16/kgpe-d16.config
boards/librem13v2/librem13v2.config
boards/librem13v4/librem13v4.config
boards/librem15v3/librem15v3.config
boards/librem15v4/librem15v4.config
boards/t420/t420.config
boards/x220/x220.config
boards/x230-flash/x230-flash.config
boards/x230/x230.config
initrd/bin/flash.sh

to be exportedable by Makefile

Flash.sh cleanup: Fix FLASHROM_OPTIONS -> CONFIG_FLASHROM_OPTIONS

---

.gitlab-ci.yml

Adding Gitlab-CI to master, based on Fedora-32

Add gitlabci ci integration

---

.circleci/config.yml
.gitlab-ci.yml

Testing PR autobuilding at the same time (Want to see if PR builds automatically and produces equivalent artifacts

CIs: restrict cache, clean past build artifacts.

---

modules/libpng

Libpng download from GitHub

---

.circleci/config.yml
.gitlab-ci.yml

- move qemu-coreboot to be built last 
- add t430 and t430-flash boards

CIs: add t430 and t430-flash boards to CircleCi and GitlabCI

---

initrd/bin/gui-init
initrd/init

This PR enables users to check the build-in hardware (CPU, RAM size, size of disk).

Add systeminfo menu option

---

initrd/bin/gpg-gui.sh

It might come in handy to be able to export the public keys stored in the keyring of heads. This PR shall make it possible and thus adds a menu option to do so.

Add option to export pubkey

---

initrd/bin/oem-factory-reset

Guard TPM-related bits by checking CONFIG_TPM = y

oem-factory-reset: Handle non-TPM case

---

modules/fbwhiptail

modules/fbwhiptail: fixate to latest commit ID for future reproducibility of same heads commit ID

---

.gitlab-ci.yml.deprecated

For details and failed experiments, see https://github.com/osresearch/heads/pull/851

GitlabCI now deprecated. 

---

.circleci/config.yml

Successful build under https://app.circleci.com/pipelines/github/tlaurion/heads/667/workflows/8094ff3d-93cd-4ff6-a3c7-8f0173e3cec9/jobs/719

CircleCI: seperate build error from details for KGPE-D16 (par to other boards)

---

boards/t430-hotp-maximized/t430-hotp-maximized.config
boards/t430-maximized/t430-maximized.config
boards/x230-hotp-maximized/x230-hotp-maximized.config
boards/x230-maximized/x230-maximized.config

Doesn't change functionality.  Will let here a day or two and merge after.

xx30 boards: correct documentation, typos

---

Makefile
modules/coreboot
modules/linux
modules/musl-cross

Part of #1002 which can be applied on its own and might be generally useful.

Build enhancements

---

initrd/bin/seal-totp

Enable use of TOTP devices without a camera

Display TOTP secret as text

---

initrd/bin/gui-init

CONFIG_HOTPKEY is not exported to the initrd, check for binary presence.

Check for /bin/hotp_verification instead of CONFIG_HOTPKEY

---

modules/dropbear

Switch to mirror https://mirror.dropbear.nl/
Signed-off-by: Jonathon Hall <jonathon.hall@puri.sm>

dropbear: Use mirror, main host is down

---

initrd/bin/oem-factory-reset

oem-factory-reset: Add missing newline to prompt

---

initrd/bin/flash.sh

talos II: die when tgz archive is corrupt

---

initrd/etc/functions

@JonathonHall-Purism please review.

init: add 2 seconds pause on die, 1 second on warning so users see console messages

---

initrd/bin/kexec-save-default
initrd/bin/kexec-select-boot
initrd/bin/oem-factory-reset

Fixes #1270
@JonathonHall-Purism that seems to do it.

/boot: make sure operations requiring to be happening under /boot are under subshells

---

boards/qemu-coreboot-fbwhiptail-tpm1-hotp/qemu-coreboot-fbwhiptail-tpm1-hotp.md

Fix reported typo under #1314

---

initrd/bin/flash.sh

Improve speed by pre-filtering only for lines containing any tokens of interest to flashrom_progress_tokenize().
Improve reliability by avoiding dropping tokens that cross a stream buffer boundary.  Occasionally, a token could be missed if it crosses a stream buffer boundary, due to read timing out too quickly before the next buffer is flushed.  If this was a state-changing token, flashrom_progress() would hang forever.
---
Purism's coreboot utility contains a copy of this same code (https://source.puri.sm/firmware/utility/-/blob/master/coreboot_util.sh#L775).  During the PureBoot 28 release cycle, I encountered a situation where coreboot_util.sh would _consistently_ hang due to the "contents..." token always crossing a stream buffer boundary - the script read "c" and then "ontents..." …

initrd/bin/flash.sh: Improve speed and reliability

---

initrd/bin/oem-factory-reset

oem-factory-reset: fix call to mount-usb --mode rw 

---

patches/newt-0.52.20.patch

This fixes #1455 without needing to change all previous menu choices.
@JonathonHall-Purism please review

newt(whiptail): fix code that was doing toupper of input

---

modules/cairo
modules/pixman

Adds up to https://github.com/linuxboot/heads/issues/1198

switch back from web.archive.org to cairographics.org (CircleCI is rate limited)

---

.github/ISSUE_TEMPLATE/bug-report-for-everything-except-build-errors.md
.github/ISSUE_TEMPLATE/bug-report-for-heads-build-errors.md

Update issue templates to reflect current realities of forks and security Dongles in the field

---

.github/ISSUE_TEMPLATE/bug-report-for-everything-except-build-errors.md
.github/ISSUE_TEMPLATE/bug-report-for-heads-build-errors.md

Also fix gPU -> GPU
Signed-off-by: Thierry Laurion <insurgo@riseup.net>

GitHub issue templates: Version information aimed to be hidden was visible + typo fix

---

initrd/bin/kexec-select-boot

1692 Update text for TPM Primary Handle error with correct remediation steps.

---

config/coreboot-kgpe-d16_server-whiptail.config
config/coreboot-kgpe-d16_server.config
config/coreboot-kgpe-d16_workstation-usb_keyboard.config
config/coreboot-kgpe-d16_workstation.config

Superseeds https://github.com/linuxboot/heads/pull/1759 with
- signed commits
- typo correction viking -> vikings

Add Vikings HCL to boards D16 board configs

---

funding.json

This passed https://dir.floss.fund/validate validation

Floss.fund funding.json requirement

---

funding.json

This passed https://dir.floss.fund/validate validation

Floss.fund funding.json requirement: main->master typo

---

blobs/xx30/optiplex_7010_9010.sh

archive.org still having difficulties post hack of october 9th. Use dell server first then archive.org as fallback.

blobs/xx30/optiplex_7010_9010.sh: use dell server first, fallback to archive.org (archive.org still having difficilties now)

---

boards/UNTESTED_t440p-hotp-maximized/UNTESTED_t440p-hotp-maximized.config
boards/UNTESTED_w541-hotp-maximized/UNTESTED_w541-hotp-maximized.config

w541/t440p hotp variants including non-htop: fix path to non-hotp board variants

---

.circleci/config.yml
flake.nix

fix #1829 
.gitconfig containing safe dir was not under /root so not taken into consideration.

Docker image 0.2.4: Fix git dubious ownership in repository

---

BOARD_TESTERS.md

No need for review. Will wait for previous commit to master to build and will merge next.
Closes #1869 
Next: edit https://github.com/linuxboot/heads/issues/692 issue to only contain blobs description, testers under BOARD_TESTERS.md to keep track of change over time.

Board testers review

---

initrd/etc/luks-functions

@tlaurion a possible fix for https://github.com/linuxboot/heads/issues/1963
I have not tested the fix. So someone should.

fix change passphrase
